import type { BibleSkyFact } from "./types";

// Bible facts revealed by the star-discovery button during an assessment (see
// AssessmentAtmosphere.tsx) — not on the dashboard. The pool is 365 entries,
// picked by hashing the attempt id with the discovery milestone, so a given
// attempt shows a stable fact and different attempts differ.
//
// House style, worth keeping: a title of two to four words, then one or two
// sentences. Facts are structural, literary, linguistic, and historical — the
// kind of thing that reframes how the Bible is put together — rather than
// devotional lines or contested interpretive claims. Where scholarship
// genuinely differs, the wording says so ("often counted as", "in many Jewish
// orders") instead of picking a side.

export const BIBLE_SKY_FACTS: BibleSkyFact[] = [
  { title: "Three Languages", fact: "Most of the Old Testament is Hebrew, parts of Ezra and Daniel are Aramaic, and the New Testament is Greek. The Bible is multilingual from the start." },
  { title: "Late Coordinates", fact: "Chapter numbers and verse numbers were added long after the biblical books were written. They are more like map coordinates than part of the original text." },
  { title: "Chronicles Last", fact: "In many Jewish orders of the Hebrew Bible, Chronicles comes at the end. That gives the canon a very different final note than Malachi." },
  { title: "The Same OT, Different Shelves", fact: "The Hebrew Bible and Protestant Old Testament contain the same books, but they arrange them differently: Torah, Prophets, and Writings versus Law, History, Poetry, and Prophets." },
  { title: "The Twelve", fact: "Hosea through Malachi are often counted as one scroll-sized collection: the Book of the Twelve. Twelve voices, one prophetic shelf." },
  { title: "Scroll Logistics", fact: "Samuel, Kings, Chronicles, and Ezra-Nehemiah were each originally treated as single works. Our 1 and 2 divisions are partly a scroll-and-bookmaking story." },
  { title: "A Five-Book Hymnal", fact: "Psalms is not just one long playlist. It is arranged as five smaller books, each ending with a doxology." },
  { title: "Jeremiah Is Huge", fact: "By word count in many arrangements, Jeremiah is one of the biggest books in the Bible. The prophet had a lot to say and a hard century to say it in." },
  { title: "The Torah Is Massive", fact: "If the Torah is treated as one five-part work, it outweighs every other biblical book by a lot. Genesis through Deuteronomy is the Bible's great foundation slab." },
  { title: "Job Is Set Abroad", fact: "Job is not set in Jerusalem, Judah, or Israel. Its story opens in Uz, giving the book an intentionally borderland feel." },
  { title: "Job's Friends Sit Silent", fact: "Before any arguments begin, Job's friends sit with him seven days and seven nights without speaking. The silence is one of the wisest things they do." },
  { title: "Esther's Hiddenness", fact: "Esther never directly names God, yet the story is built around providence, reversal, and rescue happening behind the curtain." },
  { title: "Daniel's Placement", fact: "Daniel appears among the Writings in the Hebrew Bible, not with Isaiah, Jeremiah, Ezekiel, and the Twelve." },
  { title: "Ruth's Other Home", fact: "English Bibles place Ruth after Judges because of its setting, but Jewish ordering can place Ruth among the festival scrolls in the Writings." },
  { title: "Lamentations as a Scroll", fact: "Lamentations is one of the Megillot, the five festival scrolls, which is why OBA treats it as Writings rather than Latter Prophets." },
  { title: "Hebrews Is Anonymous", fact: "Hebrews has been treasured for centuries, but its author is not named in the book. Ancient readers debated the question too." },
  { title: "Luke's Two-Volume Work", fact: "Luke and Acts read like a two-part project: the story of Jesus, then the story of the gospel moving outward from Jerusalem." },
  { title: "A Fourfold Gospel", fact: "The early church did not keep just one Gospel voice. Matthew, Mark, Luke, and John were received together, preserving four angles on Jesus." },
  { title: "Letters Before Libraries", fact: "Paul's letters were written to real communities before they were gathered into a New Testament collection. Romans was not born as chapter six of a printed book." },
  { title: "Shortest OT Book", fact: "Obadiah is tiny, but it lands a sharp prophetic blow against Edom's pride and violence toward Judah." },
  { title: "The Two Tiny Letters", fact: "Second and Third John are the smallest books in the New Testament. Which one is actually shorter depends on whether you count Greek words or English ones." },
  { title: "Songs Everywhere", fact: "Psalms is the obvious songbook, but songs and victory poems appear across the Bible, from Exodus to Revelation." },
  { title: "Jonah Is Mostly Story", fact: "Jonah is a prophetic book, but it mostly tells a story about a prophet instead of collecting the prophet's sermons." },
  { title: "A Prophet in Exile", fact: "Ezekiel does much of his prophetic work among deported Judeans in Babylon. The book is full of visions from life after catastrophe." },
  { title: "Isaiah's Huge Horizon", fact: "Isaiah stretches from eighth-century Judah to visions of worldwide restoration. Its scale is one reason later biblical writers return to it so often." },
  { title: "The Shema", fact: "Deuteronomy 6:4 begins the Shema, one of the central confessions of Jewish prayer and memory." },
  { title: "Torah Means Teaching", fact: "Torah is often translated law, but instruction or teaching catches an important part of the word's range." },
  { title: "Former Prophets", fact: "Joshua, Judges, Samuel, and Kings are called Former Prophets because they interpret Israel's history through covenant and prophetic theology." },
  { title: "Latter Prophets", fact: "The Latter Prophets are Isaiah, Jeremiah, Ezekiel, and the Twelve. That is four scrolls, not seventeen books, in the Hebrew arrangement." },
  { title: "Ezra-Nehemiah", fact: "Ezra and Nehemiah were often handled as one work, telling a combined return-from-exile and restoration story." },
  { title: "Revelation's Genre Mix", fact: "Revelation is apocalypse, prophecy, and letter all at once. It is addressed to seven churches but thinks on a cosmic scale." },
  { title: "The Bible Is Not Linear", fact: "The Bible is a library, not a single timeline. Narrative, poetry, law, wisdom, prophecy, gospel, apocalypse, and letters sit side by side." },
  { title: "Manuscript Reality", fact: "We do not have the original biblical manuscripts. What we have is an ancient manuscript tradition of copies, translations, and carefully preserved witnesses." },
  { title: "Canon Memory", fact: "By the first century, Jewish sources already show a strong sense of a recognized Scripture collection, often described in three parts." },
  { title: "Paul's Smallest Letter", fact: "Philemon is personal, brief, and explosive: a tiny letter that presses the gospel into the social world of slavery, debt, and reconciliation." },
  { title: "James Gives Commands", fact: "James is famously direct. Its wisdom style is packed with imperatives about speech, wealth, patience, prayer, and practice." },
  { title: "The Ending of Kings", fact: "Kings ends with Jerusalem ruined, but also with a small note of hope: Jehoiachin is released from prison and given a seat at the table." },
  { title: "A Genealogy Surprise", fact: "Matthew's genealogy names women with complicated, outsider, or scandal-shadowed stories, preparing readers for a Messiah who gathers unlikely people." },
  { title: "Mark Moves Fast", fact: "Mark's Gospel loves urgency. Its favorite pace is immediately: scene after scene presses forward toward the cross." },
  { title: "John Counts Signs", fact: "John organizes much of Jesus' public ministry around signs that reveal who he is, then slows dramatically for the final night and crucifixion." },
  { title: "Sixty-Six Books", fact: "The Protestant Bible gathers 66 books: 39 in the Old Testament, 27 in the New. It is a shelf of writings, not a single volume written straight through." },
  { title: "Documents Inside the Story", fact: "Ezra and Esther reproduce official letters and decrees, embedding imperial paperwork directly inside the biblical narrative." },
  { title: "Chapters Came From Paris", fact: "The chapter divisions used in most Bibles today are usually credited to Stephen Langton, working at Paris in the early thirteenth century." },
  { title: "Verses Came Later Still", fact: "Verse numbers for the New Testament are usually credited to the printer Robert Estienne in the sixteenth century, centuries after Langton's chapters." },
  { title: "Longest Chapter", fact: "Psalm 119 is the longest chapter in the Bible, an enormous acrostic meditation built entirely around delight in God's instruction." },
  { title: "Shortest Chapter", fact: "Psalm 117 is only two verses long. It calls all nations to praise the LORD and then simply stops." },
  { title: "Psalm 119 Is Alphabetical", fact: "Psalm 119 has twenty-two sections, one for each letter of the Hebrew alphabet, and every line in a section starts with that letter." },
  { title: "Acrostic Poems", fact: "Several psalms and most of Lamentations run down the Hebrew alphabet. Many English Bibles print the letter names over Psalm 119 but hide the pattern everywhere else." },
  { title: "Lamentations Chapter Five", fact: "Lamentations chapters one through four are acrostics. Chapter five has twenty-two verses, matching the alphabet's length, but drops the acrostic form." },
  { title: "Proverbs 31 Is an Acrostic", fact: "The famous poem about the capable woman at the end of Proverbs is an alphabetical acrostic, twenty-two lines running A to Z in Hebrew." },
  { title: "Selah", fact: "Selah appears dozens of times in the Psalms and in Habakkuk. Its exact meaning is uncertain; a musical or liturgical direction is the common guess." },
  { title: "Psalm Superscriptions", fact: "Many psalms carry a heading naming a tune, an instrument, an occasion, or a person. Some traditions count those headings as verse one." },
  { title: "Two Psalm Numberings", fact: "Hebrew and Greek traditions divide the Psalms slightly differently, so a psalm can carry different numbers depending on which tradition a Bible follows." },
  { title: "Maskil and Miktam", fact: "Psalm headings use technical terms like maskil and miktam whose precise sense is no longer certain. Ancient worship had vocabulary we have partly lost." },
  { title: "David's Prayers End Early", fact: "Psalm 72 closes by declaring the prayers of David finished. Eighteen later psalms are headed as David's anyway." },
  { title: "Psalms Has Many Authors", fact: "The Psalms carry headings linking them to David, Asaph, the sons of Korah, Solomon, Moses, and others. It is a collection, not one poet's notebook." },
  { title: "Two Creation Openings", fact: "Genesis opens with a majestic seven-day account, then narrows to a garden, a man, and a woman. The two movements work together as an introduction." },
  { title: "Genesis Ends in Egypt", fact: "Genesis begins with the cosmos and ends with a coffin in Egypt. The Torah's first book closes on a promise still waiting to be kept." },
  { title: "The Torah Ends Outside", fact: "Deuteronomy ends with Israel still outside the land, looking in. The Torah closes on the edge of fulfillment rather than inside it." },
  { title: "Five Books of Moses", fact: "Torah, Pentateuch, and Books of Moses all name the same five-book collection. Different traditions, one foundational unit." },
  { title: "Pentateuch Means Five", fact: "Pentateuch comes from Greek words meaning five scrolls. The name describes the packaging as much as the content." },
  { title: "Genesis Means Beginning", fact: "The Greek name Genesis means origin or beginning. Hebrew tradition instead names the book Bereshit, its opening word." },
  { title: "Hebrew Books by First Words", fact: "Hebrew names for the Torah's books come from their opening words: Bereshit, Shemot, Vayikra, Bemidbar, Devarim." },
  { title: "Exodus Means Going Out", fact: "Exodus takes its name from the Greek for departure. The Hebrew name, Shemot, means names, from the list that opens the book." },
  { title: "Numbers and Its Censuses", fact: "The English name Numbers comes from the censuses in the book. The Hebrew name, Bemidbar, means in the wilderness, which fits the story better." },
  { title: "Deuteronomy Means Second Law", fact: "Deuteronomy comes from Greek for second law, reflecting how it restates the covenant for a new generation about to enter the land." },
  { title: "Leviticus and the Levites", fact: "Leviticus is named for the Levites, though the book addresses Israel broadly. It is largely instruction about worship, holiness, and priesthood." },
  { title: "Judges Has No King", fact: "The book of Judges circles a refrain about there being no king in Israel, with everyone doing what was right in their own eyes." },
  { title: "Judges Are Not Courtroom Judges", fact: "The judges of the book are deliverers and leaders raised up in crises, not officials presiding over trials." },
  { title: "Ruth Is Four Chapters", fact: "Ruth is short enough to read in one sitting, yet it lands a genealogy that runs straight to David and, later, into Matthew's opening chapter." },
  { title: "Samuel Has No Samuel Ending", fact: "Samuel is named for a prophet who dies partway through. The book keeps going, because its real subject is the rise of kingship." },
  { title: "Kings Covers Centuries", fact: "Kings runs from Solomon's reign to the fall of Jerusalem, tracking a divided kingdom and a long parade of rulers north and south." },
  { title: "Chronicles Retells", fact: "Chronicles covers ground already told in Samuel and Kings, but from a different angle, with heavy attention to temple, worship, and David's line." },
  { title: "Nine Chapters of Genealogy", fact: "Chronicles opens with roughly nine chapters of genealogy before its narrative starts. The lists are the book's way of establishing identity." },
  { title: "Walls and Covenant", fact: "Ezra and Nehemiah tell of return from exile, rebuilding, and reform. Walls, worship, and covenant renewal share the stage." },
  { title: "Esther in Persia", fact: "Esther is set in the Persian court, far from Jerusalem. It is a diaspora story about survival under a foreign empire." },
  { title: "Purim's Origin Story", fact: "Esther explains the origin of Purim, tying a festival of feasting and gift-giving to a reversal of a decree of destruction." },
  { title: "Job Is Mostly Poetry", fact: "Job opens and closes in prose, but the long middle is poetry: cycles of speeches between Job and his friends, then God's answer." },
  { title: "God Answers With Questions", fact: "When God finally speaks to Job, the reply is a torrent of questions about creation rather than a tidy explanation of suffering." },
  { title: "Ecclesiastes and Hevel", fact: "Ecclesiastes returns again and again to a Hebrew word often rendered vanity, meaning something like vapor, breath, or fleeting mist." },
  { title: "Qoheleth", fact: "The speaker of Ecclesiastes is called Qoheleth, a term connected to gathering or assembly, often rendered Teacher or Preacher." },
  { title: "Song of Songs", fact: "The title Song of Songs is a Hebrew superlative, like King of kings. It means the greatest song of them all." },
  { title: "Songs Without God's Name", fact: "Like Esther, the Song of Songs never plainly names God. One word near its end may hide a shortened form of the divine name, and translators disagree." },
  { title: "Five Festival Scrolls", fact: "Song of Songs, Ruth, Lamentations, Ecclesiastes, and Esther form the Megillot, read at five points in the Jewish festival year." },
  { title: "Isaiah Opens the Gospels", fact: "All four Gospels introduce John the Baptist by quoting Isaiah. Every one of them walks in through the same prophetic doorway." },
  { title: "Jeremiah's Scribe", fact: "Jeremiah's words are written down by Baruch, a scribe named in the book. Prophecy reached the page through someone's hand." },
  { title: "A Scroll Burned", fact: "Jeremiah tells of a king slicing a scroll column by column and burning it. The book records the scroll being written again." },
  { title: "Ezekiel Eats a Scroll", fact: "Ezekiel is told to eat a scroll before speaking. He reports that it tasted as sweet as honey." },
  { title: "Ezekiel's Dry Bones", fact: "Ezekiel's valley of dry bones is a vision of national resurrection, and it became one of the most reused images in later art and song." },
  { title: "Daniel Switches Language", fact: "Daniel begins in Hebrew, shifts to Aramaic for a long central stretch, and returns to Hebrew. The seam is right there in the text." },
  { title: "Hosea's Marriage", fact: "Hosea's own marriage becomes a prophetic sign. His family's names are turned into messages about covenant, judgment, and mercy." },
  { title: "Joel and the Locusts", fact: "Joel builds from a devastating locust plague to the day of the LORD, then to an outpouring of the Spirit on all flesh." },
  { title: "Amos the Herdsman", fact: "Amos describes himself as a herdsman and tender of sycamore figs, not a professional prophet. He arrives from outside the guild." },
  { title: "Obadiah in One Chapter", fact: "Obadiah is a single chapter, the shortest book in the Old Testament, aimed squarely at Edom." },
  { title: "Jonah's Missing Ending", fact: "Jonah ends on a question from God about mercy toward a great city. The prophet never answers, and neither does the book." },
  { title: "Micah's Famous Line", fact: "Micah asks what the LORD requires and answers with justice, mercy, and walking humbly. It has become one of the Bible's most quoted summaries." },
  { title: "Nahum and Nineveh", fact: "Nineveh repents in Jonah. In Nahum, the same city faces judgment. The two books make a striking pair on the same shelf." },
  { title: "Habakkuk Argues", fact: "Habakkuk opens by complaining to God about violence and injustice, and the book is structured as a genuine back-and-forth." },
  { title: "Zephaniah's Long Pedigree", fact: "Zephaniah's opening traces his ancestry back four generations, unusually far for a prophetic superscription." },
  { title: "Haggai Is Dated", fact: "Haggai's messages carry precise dates tied to a Persian king's reign, anchoring the book firmly in a rebuilding project." },
  { title: "Zechariah's Night Visions", fact: "Zechariah opens with a sequence of strange night visions: horses, horns, a measuring line, a lampstand, a flying scroll." },
  { title: "Malachi Means My Messenger", fact: "The name Malachi means my messenger, which has led some readers to ask whether it is a title rather than a personal name." },
  { title: "Malachi's Disputations", fact: "Malachi is built as a series of disputes: God makes a claim, the people push back, and God answers the objection." },
  { title: "Prophets Are Not Only Predictors", fact: "Prophetic books spend most of their space on covenant, justice, worship, and warning. Prediction is part of the work, not the whole job." },
  { title: "Writing and Non-Writing Prophets", fact: "Elijah and Elisha loom large in Kings but left no books. Isaiah and Jeremiah left both a reputation and a scroll." },
  { title: "Hebrew Runs Right to Left", fact: "Hebrew is written right to left, so an open Hebrew Bible turns pages in the opposite direction from an English one." },
  { title: "Consonants First", fact: "Ancient Hebrew was written with consonants. Vowel markings were added much later by scribes preserving how the text was read aloud." },
  { title: "The Masoretes", fact: "Medieval Jewish scribes called Masoretes added vowel points, accents, and marginal notes to safeguard the reading of the Hebrew text." },
  { title: "Ketiv and Qere", fact: "Hebrew manuscripts sometimes note that a word is written one way but read another. The margin preserves both the written and the spoken tradition." },
  { title: "Koine Greek", fact: "The New Testament is written in Koine, the common Greek of the eastern Mediterranean, not the polished literary Greek of classical Athens." },
  { title: "No Spaces", fact: "Ancient manuscripts were often written in continuous script with little spacing or punctuation. Reading was a skill, not a glance." },
  { title: "Uppercase Only", fact: "Early Greek manuscripts were written in capital letters. Lowercase minuscule manuscripts came into wide use centuries later." },
  { title: "Papyrus and Parchment", fact: "Biblical texts were copied onto papyrus and onto parchment made from animal skin. Material choice affected cost, durability, and format." },
  { title: "Scroll to Codex", fact: "Early Christians adopted the codex, the bound book form, unusually early. It let a reader flip between passages instead of unrolling." },
  { title: "The Septuagint", fact: "The Septuagint is an ancient Greek translation of the Hebrew scriptures, widely used in the Greek-speaking world of the first century." },
  { title: "Seventy Translators", fact: "The name Septuagint comes from a tradition about seventy or seventy-two translators, and it is often abbreviated with the Roman numeral LXX." },
  { title: "Targums", fact: "Targums are Aramaic renderings of the Hebrew scriptures, produced where Aramaic had become the everyday language of many Jewish communities." },
  { title: "The Peshitta", fact: "The Peshitta is the standard Bible of Syriac-speaking churches, one of the great early translation traditions of the Christian East." },
  { title: "The Vulgate", fact: "Jerome's Latin Vulgate shaped Western Christian vocabulary for a thousand years. Many familiar theological terms travel through Latin." },
  { title: "Dead Sea Scrolls", fact: "Manuscripts found near the Dead Sea pushed our oldest Hebrew biblical copies many centuries earlier than what scholars had before." },
  { title: "The Great Isaiah Scroll", fact: "One Dead Sea manuscript preserves nearly the whole book of Isaiah, and it remains one of the most studied biblical manuscripts anywhere." },
  { title: "Codex Sinaiticus", fact: "Codex Sinaiticus is a very early and remarkably complete Greek Bible manuscript, and a cornerstone of New Testament textual study." },
  { title: "Codex Vaticanus", fact: "Codex Vaticanus is another major early Greek manuscript, and comparing it with Sinaiticus is a standard exercise in textual criticism." },
  { title: "Textual Criticism", fact: "Textual criticism compares manuscripts to reconstruct the earliest recoverable wording. Footnotes in modern Bibles are its visible tip." },
  { title: "Footnote Variants", fact: "When a Bible footnote says some manuscripts read differently, it is reporting real evidence, not hedging about the translation." },
  { title: "Nomina Sacra", fact: "Early Christian scribes abbreviated sacred names with special contracted forms and an overline, a scribal habit visible across manuscripts." },
  { title: "The Tetragrammaton", fact: "The divine name in Hebrew is written with four consonants. Many English Bibles render it LORD in small capitals out of longstanding reverence." },
  { title: "Small Capitals Matter", fact: "In many English Bibles the typography carries information: LORD in small capitals marks the divine name, while plain Lord does not." },
  { title: "Elohim", fact: "Elohim is a common Hebrew word for God that is grammatically plural in form but regularly takes singular verbs when it refers to Israel's God." },
  { title: "El Shaddai", fact: "El Shaddai is one of several divine titles in the Torah. Its precise meaning is debated; God Almighty is the traditional rendering." },
  { title: "Amen", fact: "Amen is a Hebrew word carried untranslated into Greek, Latin, and English. It signals firmness, trust, and agreement." },
  { title: "Hallelujah", fact: "Hallelujah is Hebrew for praise the LORD, and it travels into Greek and English almost unchanged." },
  { title: "Hosanna", fact: "Hosanna began as a cry meaning save now. By the first century it had also become an acclamation of welcome." },
  { title: "Messiah and Christ", fact: "Messiah is Hebrew for anointed one. Christ is the Greek translation of the same idea, not a surname." },
  { title: "Gospel Means Good News", fact: "Gospel translates a Greek word for good news or glad announcement. It named a message before it named a kind of book." },
  { title: "Apostle Means Sent One", fact: "Apostle comes from a Greek word meaning one who is sent. The title describes a commission, not a rank alone." },
  { title: "Church Means Assembly", fact: "The Greek word behind church refers to a gathered assembly. In the first century it named people meeting, not a building." },
  { title: "Baptize Means Immerse", fact: "The Greek verb behind baptize carries the sense of dipping or immersing, which is why the word was borrowed rather than translated." },
  { title: "Angel Means Messenger", fact: "The words translated angel in Hebrew and Greek both mean messenger. Context decides whether a human or heavenly one is meant." },
  { title: "Satan Means Accuser", fact: "The Hebrew term behind Satan means adversary or accuser. It functions as a description before it settles into a name." },
  { title: "Sheol and Hades", fact: "Sheol in Hebrew and Hades in Greek both name the realm of the dead. English Bibles vary in how they render them." },
  { title: "Gehenna", fact: "Gehenna derives from the name of a valley outside Jerusalem. The place name became an image for final judgment." },
  { title: "Hapax Legomena", fact: "Some biblical words appear only once in the whole Bible. Translating a hapax legomenon means working with very little comparative evidence." },
  { title: "Word Order Differs", fact: "Hebrew and Greek arrange sentences differently from English, so translation always involves rebuilding, not just swapping words." },
  { title: "Parallelism Over Rhyme", fact: "Hebrew poetry rhymes ideas rather than sounds, pairing lines that echo, sharpen, or reverse each other." },
  { title: "Chiasm", fact: "Biblical writers often arrange material in mirrored patterns, where the outer elements match and the center carries the weight." },
  { title: "Inclusio", fact: "An inclusio frames a passage by repeating a phrase at its start and end, marking where a unit begins and stops." },
  { title: "Wycliffe's English Bible", fact: "Late medieval English translations associated with John Wycliffe put scripture into English long before printing made copies cheap." },
  { title: "Tyndale's Phrases", fact: "William Tyndale's English renderings shaped later translations so strongly that many familiar phrases can be traced back to his work." },
  { title: "Printing Changed Everything", fact: "The printing press turned Bibles from expensive hand-copied objects into something a household could plausibly own." },
  { title: "KJV Italics", fact: "The King James Version prints some words in italics to mark supplied words with no direct equivalent in the underlying text." },
  { title: "Red Letter Editions", fact: "Printing the words of Jesus in red is a publishing convention from the modern era, not a feature of ancient manuscripts." },
  { title: "Formal and Functional", fact: "Translations sit on a spectrum from closely following source structure to prioritizing natural receptor language. Both aim at faithfulness." },
  { title: "Translation Committees", fact: "Most major modern Bible translations are produced by committees, so no single translator's preferences run unchecked through the text." },
  { title: "Public Domain Bibles", fact: "Some translations, including the King James Version and the Berean Standard Bible, can be freely quoted and reproduced without permission." },
  { title: "Aramaic in the Gospels", fact: "The Gospels preserve occasional Aramaic words, sometimes with an immediate translation supplied for readers who did not know the language." },
  { title: "Abba", fact: "Abba is an Aramaic word for father that the New Testament keeps untranslated in a few places, then glosses for Greek readers." },
  { title: "Talitha Koum", fact: "Mark preserves the Aramaic phrase Talitha koum and translates it on the spot, a small window into the language of the scene." },
  { title: "Maranatha", fact: "Maranatha is an Aramaic expression preserved in Paul's Greek, showing early worship vocabulary crossing language lines." },
  { title: "Latin Loanwords", fact: "The Gospels contain Greek words borrowed from Latin, a trace of Roman administration in the everyday speech of the region." },
  { title: "Alpha and Omega", fact: "Alpha and omega are the first and last letters of the Greek alphabet, which is why the pairing means beginning and end." },
  { title: "Amanuensis", fact: "Paul often dictated. In Romans the scribe Tertius pauses to greet the readers in his own name." },
  { title: "Paul's Own Hand", fact: "Paul sometimes notes that he is writing a closing line himself, a signature gesture that authenticated an ancient dictated letter." },
  { title: "Ancient Letter Form", fact: "Greco-Roman letters opened with sender, recipient, and greeting. The New Testament letters follow that shape, then bend it theologically." },
  { title: "Letters Were Read Aloud", fact: "Most people met these letters by hearing them read to a gathered assembly, not by reading privately from a personal copy." },
  { title: "Carriers of Letters", fact: "Letters traveled by courier. Named individuals in the closing greetings sometimes carried the very letter that mentions them." },
  { title: "Chapter Breaks Can Mislead", fact: "A chapter break sometimes lands mid-argument. Reading across the number often reveals a sentence the division interrupted." },
  { title: "Verse Numbers Encourage Slicing", fact: "Verse numbering makes quoting easy and makes it equally easy to lift a line away from the paragraph that explains it." },
  { title: "Scribes Counted Letters", fact: "Masoretic notes tally the verses, words, and letters of a book and mark its midpoint. Counting was a quality-control system." },
  { title: "Copying by Hand", fact: "Every biblical text before printing was copied by hand. Scribal culture developed careful checks precisely because hands slip." },
  { title: "Matthew's Five Blocks", fact: "Matthew gathers Jesus' teaching into five large discourses, a shape many readers connect with the five books of the Torah." },
  { title: "The Sermon on the Mount", fact: "Matthew 5 through 7 is one sustained block of teaching, the longest continuous stretch of Jesus speaking in that Gospel." },
  { title: "Kingdom of Heaven", fact: "Matthew usually says kingdom of heaven where Mark and Luke say kingdom of God, a stylistic preference running through the book." },
  { title: "Matthew Quotes Constantly", fact: "Matthew repeatedly stops to note that something happened to fulfill what was spoken. The Old Testament is never far from the page." },
  { title: "Mark Is the Shortest", fact: "Mark is the shortest of the four Gospels, and its compression is part of its energy rather than a sign of thinness." },
  { title: "Mark's Endings", fact: "Ancient manuscripts of Mark end at different points, which is why modern Bibles usually mark the final verses with a note." },
  { title: "Mark's Sandwiches", fact: "Mark often starts one story, interrupts it with another, then finishes the first. The interruption interprets the frame." },
  { title: "Luke Writes to Theophilus", fact: "Luke and Acts are both addressed to Theophilus, tying the two volumes together with a shared dedication." },
  { title: "Luke's Prologue", fact: "Luke opens with a formal preface describing careful investigation and orderly arrangement, the conventions of ancient historical writing." },
  { title: "Luke's Parables", fact: "Several of the best-known parables, including the good Samaritan and the prodigal son, appear only in Luke." },
  { title: "Luke Notices Outsiders", fact: "Luke gives sustained attention to the poor, to women, to Samaritans, and to those on the social margins of his world." },
  { title: "John's Long Farewell", fact: "John devotes several chapters to one final evening of teaching and prayer, slowing the narrative dramatically before the arrest." },
  { title: "John's I Am Sayings", fact: "John records a series of I am statements: bread, light, door, shepherd, resurrection, way, vine." },
  { title: "John's Missing Parables", fact: "John contains no parables of the kind found in the Synoptics. Its teaching comes as extended discourse instead." },
  { title: "The Synoptic Gospels", fact: "Matthew, Mark, and Luke are called Synoptic because they can be set side by side and viewed together. John charts a different course." },
  { title: "The Synoptic Problem", fact: "Explaining the overlaps and differences among Matthew, Mark, and Luke is a long-running scholarly conversation with several proposals." },
  { title: "Acts Ends Abruptly", fact: "Acts closes with Paul in Rome, teaching without hindrance. The story stops mid-mission rather than tying up every thread." },
  { title: "Acts and the We Passages", fact: "Parts of Acts shift into first person plural, a feature readers have long noticed and discussed." },
  { title: "Pentecost in Acts", fact: "Acts sets the outpouring of the Spirit at Pentecost, a harvest festival that already drew pilgrims to Jerusalem from many regions." },
  { title: "Paul's Letters by Length", fact: "Paul's letters descend by length twice over: first the ones to churches, Romans down to Thessalonians, then the ones to individuals." },
  { title: "Romans Is a Long Argument", fact: "Romans builds a sustained theological argument across many chapters, and it is Paul's longest surviving letter." },
  { title: "Corinthian Correspondence", fact: "Paul's Corinthian letters reference other exchanges, suggesting the surviving letters are part of a longer conversation." },
  { title: "Galatians Skips the Thanks", fact: "Paul usually opens with thanksgiving. In Galatians he moves straight to astonishment, and the omission is itself a signal." },
  { title: "Prison Letters", fact: "Several letters attributed to Paul refer to his imprisonment, which is why Ephesians, Philippians, Colossians, and Philemon are often grouped." },
  { title: "Philippians and Joy", fact: "Philippians returns to joy and rejoicing repeatedly, which is striking given the letter's references to chains." },
  { title: "Colossians and Philemon", fact: "Colossians and Philemon share names in their greetings, suggesting the two letters traveled in the same direction." },
  { title: "Thessalonian Letters", fact: "Paul's Thessalonian letters give unusual attention to the return of Christ and to how a waiting community should live in the meantime." },
  { title: "Pastoral Epistles", fact: "First and Second Timothy and Titus are often grouped as the Pastoral Epistles because they address leadership and church order." },
  { title: "Hebrews Is a Sermon", fact: "Hebrews calls itself a word of exhortation and reads more like a sustained sermon than a typical letter." },
  { title: "Hebrews and Melchizedek", fact: "Hebrews builds an extended argument around Melchizedek, a figure who appears only briefly in Genesis and once in the Psalms." },
  { title: "General Epistles", fact: "James through Jude are often called General or Catholic Epistles because they address broad audiences rather than one named city." },
  { title: "James and Wisdom", fact: "James reads like wisdom literature in a Christian key, closer in texture to Proverbs than to Romans." },
  { title: "Peter Writes to Exiles", fact: "First Peter addresses readers as sojourners and exiles scattered across provinces of Asia Minor." },
  { title: "Second Peter and Jude", fact: "Second Peter and Jude share striking overlaps in content and phrasing, a relationship long noticed by readers." },
  { title: "John's Letters Are Short", fact: "The three letters of John are brief, and two of them are among the shortest books in the Bible." },
  { title: "Second John's Elder", fact: "Second John opens from the elder to the elect lady, an address that has invited centuries of interpretation." },
  { title: "Jude's Doxology", fact: "Jude ends with one of the most quoted blessings in the New Testament, a closing far larger than the letter's size suggests." },
  { title: "Revelation's Seven Churches", fact: "Revelation opens with messages to seven specific congregations in Asia Minor, each addressed in its own local situation." },
  { title: "Patmos", fact: "Revelation places its visionary on Patmos, a small Aegean island, which grounds a cosmic book in a specific location." },
  { title: "Revelation's Sevens", fact: "Revelation is organized around sevens: churches, seals, trumpets, bowls. The number structures the book's movement." },
  { title: "Revelation Reuses Images", fact: "Revelation is saturated with Old Testament imagery from Daniel, Ezekiel, Isaiah, and Exodus, rarely quoting but constantly echoing." },
  { title: "A New Jerusalem", fact: "Revelation ends not with escape from the world but with a city coming down, and with God dwelling among people." },
  { title: "No Temple in the City", fact: "In Revelation's final vision the city has no temple, because the presence that a temple housed now fills the whole place." },
  { title: "The Bible's Last Word", fact: "Revelation closes with an invitation and a blessing, ending the Christian canon on welcome rather than on warning." },
  { title: "Genesis to Revelation", fact: "The Christian canon runs from a garden to a city, and both scenes feature a tree and a river." },
  { title: "Two Testaments, One Story", fact: "Testament here means covenant. The names Old and New describe covenants before they describe halves of a book." },
  { title: "The Silent Centuries", fact: "Between the latest Old Testament writings and the New Testament lies a long stretch of history that shaped the world of the Gospels." },
  { title: "Second Temple Judaism", fact: "The Judaism of the New Testament era was diverse, with Pharisees, Sadducees, Essenes, and others holding differing convictions." },
  { title: "Pharisees and Sadducees", fact: "Pharisees and Sadducees differed on scripture, tradition, and resurrection. The Gospels assume readers know they were not one bloc." },
  { title: "Synagogue and Temple", fact: "First-century Jewish life involved both the Jerusalem temple and local synagogues. The Gospels and Acts move between the two." },
  { title: "Sanhedrin", fact: "The Sanhedrin was a Jewish council with judicial authority under Roman oversight. It appears at pivotal moments in the Gospels and Acts." },
  { title: "Roman Roads", fact: "The spread of the early Christian movement rode partly on Roman roads and shipping lanes built for empire, not for mission." },
  { title: "Roman Citizenship", fact: "Acts reports that Paul's Roman citizenship changed how officials could treat him, and he invokes it more than once." },
  { title: "Governors and Client Kings", fact: "Rome ruled the region through a mix of governors and local client rulers, which is why the Gospels name several overlapping authorities." },
  { title: "Which Caesar?", fact: "Only Luke names the emperors, dating his account by Augustus and Tiberius. The other three Gospels say Caesar without ever saying which one." },
  { title: "Crucifixion Was Roman", fact: "Crucifixion was a Roman method of public execution reserved largely for slaves, rebels, and the lowest ranks of provincial society." },
  { title: "Golgotha", fact: "Golgotha is an Aramaic name that the Gospels translate as place of the skull. The narrators pause to explain it." },
  { title: "The Titulus", fact: "The Gospels report an inscription placed on the cross naming the charge, and John notes it was written in more than one language." },
  { title: "Tombs and Stones", fact: "First-century rock-cut tombs with a rolling stone are known from archaeology, matching the kind of tomb the Gospels describe." },
  { title: "Women at the Tomb", fact: "All four Gospels place women at the tomb first, a detail every one of them preserves despite differing in other particulars." },
  { title: "The Emmaus Road", fact: "Luke tells of a long walk in which the risen Jesus explains the scriptures before he is recognized at a meal." },
  { title: "Fishing on the Sea of Galilee", fact: "The Sea of Galilee is a freshwater lake, and a working fishing economy around it sits behind many Gospel scenes." },
  { title: "Nazareth Was Small", fact: "Nazareth was a modest village. The question about whether anything good could come from it reflects that obscurity." },
  { title: "Bethlehem Means House of Bread", fact: "The name Bethlehem means house of bread, a detail readers have long enjoyed alongside Bethlehem's role in the Gospels." },
  { title: "Passover", fact: "Passover commemorates the exodus from Egypt, and its timing frames the final week of Jesus' life in all four Gospels." },
  { title: "Unleavened Bread", fact: "The festival of Unleavened Bread runs alongside Passover, and the imagery of removing leaven recurs in Paul's letters." },
  { title: "Weeks and Pentecost", fact: "The festival of Weeks falls fifty days after Passover season, which is why its Greek name, Pentecost, means fiftieth." },
  { title: "Booths", fact: "During the festival of Booths, Israel lived in temporary shelters, remembering the wilderness years in a deliberately uncomfortable way." },
  { title: "Day of Atonement", fact: "The Day of Atonement is the most solemn day in Leviticus' calendar, and Hebrews reasons from its ritual at length." },
  { title: "The Scapegoat", fact: "Leviticus describes one goat sent away bearing the people's guilt. The English word scapegoat comes from that ritual." },
  { title: "Sabbath Rhythm", fact: "The Sabbath sets a weekly rhythm of rest that Genesis grounds in creation and Deuteronomy grounds in liberation from slavery." },
  { title: "Sabbath Year", fact: "The Torah prescribes a rest for the land every seventh year, extending Sabbath logic from people to soil." },
  { title: "Jubilee", fact: "Leviticus describes a fiftieth year of release, with debts cancelled and land returned. It is Sabbath thinking scaled up to a generation." },
  { title: "New Moon Festivals", fact: "Israel's calendar was lunar, so new moons marked months, and the prophets reference new moon observances alongside Sabbaths." },
  { title: "The Hebrew Calendar", fact: "Biblical months follow the moon while festivals follow the harvest, so the calendar has to reconcile two different clocks." },
  { title: "Days Begin at Evening", fact: "In the biblical reckoning a day begins at sundown, which is why evening and morning frame the days of Genesis 1." },
  { title: "Watches of the Night", fact: "The night was divided into watches, and the Gospels use that framework when describing events before dawn." },
  { title: "The Third Hour", fact: "Time of day is often given in hours counted from sunrise, so the third hour means mid-morning rather than three in the morning." },
  { title: "A Cubit", fact: "A cubit is roughly the length from elbow to fingertip. Ancient measures were body-based, so exact modern equivalents vary." },
  { title: "A Talent", fact: "A talent was a large unit of weight, and as money it represented an enormous sum. Parables using it are trading in extremes." },
  { title: "A Denarius", fact: "A denarius is commonly described as about a day's wage for a laborer, which sets the scale for several parables." },
  { title: "The Widow's Coins", fact: "The coins in the widow's offering are the smallest denomination mentioned in the Gospels, which is exactly the narrative point." },
  { title: "Thirty Pieces of Silver", fact: "The sum named in the betrayal narrative echoes a figure that already appears in Exodus and in Zechariah." },
  { title: "Shekel", fact: "The shekel began as a weight before it became a coin, which is why early references speak of weighing out silver." },
  { title: "An Ephah and a Homer", fact: "Dry measures like the ephah and the homer appear in law, prophecy, and narrative, and the prophets condemn tampering with them." },
  { title: "Honest Weights", fact: "The Torah and the Prophets repeatedly condemn false weights and measures, treating a rigged scale as a matter of covenant faithfulness." },
  { title: "Gleaning Laws", fact: "The Torah requires leaving the edges of a field unharvested for the poor and the foreigner. Ruth's story runs on that provision." },
  { title: "The Kinsman-Redeemer", fact: "Israelite law provided for a relative who could redeem land or family. Ruth turns that legal role into the hinge of the plot." },
  { title: "Cities of Refuge", fact: "The Torah designates cities where someone who killed accidentally could flee, separating manslaughter from murder." },
  { title: "Firstfruits", fact: "Offering the first of a harvest, before knowing how the rest would turn out, was an act of trust as much as of ritual." },
  { title: "Tithes", fact: "Tithing appears in narrative before it appears in law, showing up in Genesis well before Leviticus formalizes it." },
  { title: "Clean and Unclean", fact: "Ritual purity in Leviticus is not the same as moral guilt. The categories concern access to worship rather than personal wickedness." },
  { title: "Kosher Categories", fact: "Leviticus and Deuteronomy classify animals for eating. Acts records a vision that reframes those boundaries for the early church." },
  { title: "The Tabernacle Moves", fact: "Before the temple, Israel worshiped at a portable tent that traveled with the people. Mobility was the design brief." },
  { title: "Temple and Rebuilding", fact: "Solomon's temple is destroyed, a second is rebuilt after exile, and that second temple is the one standing in the Gospels." },
  { title: "The Ark of the Covenant", fact: "The ark is a chest housing covenant tokens. It looms over Samuel and Kings and then quietly disappears from the narrative." },
  { title: "Urim and Thummim", fact: "Priestly objects called Urim and Thummim were used for discerning decisions. The texts never explain how they worked." },
  { title: "Ephod and Breastpiece", fact: "The high priest's garments carry stones representing the tribes, so the priest wears the whole people into the sanctuary." },
  { title: "Twelve Tribes", fact: "The twelve tribes are counted differently in different lists, because Levi and Joseph's sons are handled in more than one way." },
  { title: "Levites Get No Land", fact: "Levi receives no tribal territory. Their inheritance is described as the LORD himself, which reshapes the whole land allotment." },
  { title: "Judges Before Kings", fact: "Israel is led by judges before it has kings, and Samuel presents the shift to monarchy as a fraught request." },
  { title: "The Divided Kingdom", fact: "After Solomon the kingdom splits into a northern and a southern realm, and Kings then tracks two parallel royal lines." },
  { title: "Israel and Judah", fact: "In the divided period Israel names the northern kingdom and Judah the southern, so the same word can mean different things by context." },
  { title: "Samaria and Jerusalem", fact: "Samaria was the northern capital and Jerusalem the southern. The later tension between Samaritans and Judeans has deep roots." },
  { title: "Assyria and Exile", fact: "Assyria conquers the northern kingdom, and deportation reshapes the region's population long before Babylon arrives." },
  { title: "Babylon and Exile", fact: "Babylon destroys Jerusalem and its temple and deports many from Judah. Exile becomes a defining experience in the prophets and psalms." },
  { title: "Persia and Return", fact: "Persian policy allowed exiled peoples to return and rebuild, which is the political backdrop for Ezra, Nehemiah, Haggai, and Zechariah." },
  { title: "Cyrus in Isaiah", fact: "Isaiah names a Persian king in a strikingly positive role, an unusual move in a prophetic book addressed to Israel." },
  { title: "Forty Keeps Recurring", fact: "Forty recurs across the Bible for periods of testing and formation: the rain, the wilderness years, the days of fasting." },
  { title: "Seven and Completeness", fact: "Seven carries a sense of fullness across biblical literature, from creation week to the sevens structuring Revelation." },
  { title: "Why Twelve Disciples", fact: "Twelve is tied to the tribes, which is part of why the choosing of twelve disciples reads as a deliberate signal." },
  { title: "Seventy Years", fact: "Jeremiah names seventy years for the exile, and Daniel and Chronicles both reach back to that figure to reckon where they stand." },
  { title: "Numbers Can Be Symbolic", fact: "Biblical numbers often carry meaning as well as quantity, which is why apocalyptic literature counts so carefully." },
  { title: "Genealogies Can Skip", fact: "Biblical genealogies sometimes select and compress rather than list every generation. The word for father can span more than one link." },
  { title: "Matthew's Fourteens", fact: "Matthew organizes his genealogy into three groups of fourteen, and he tells the reader he has done so." },
  { title: "Two Genealogies", fact: "Matthew and Luke both give genealogies of Jesus, and they differ. Explaining the difference is an old interpretive question." },
  { title: "Named and Unnamed", fact: "Many memorable biblical figures are never named, including Pharaoh's daughter, Jephthah's daughter, and the Samaritan woman at the well." },
  { title: "Deborah Leads", fact: "Deborah is described as both a prophet and a judge, leading Israel to victory. The song in Judges 5 is credited to her and Barak together." },
  { title: "Huldah the Prophet", fact: "When a scroll is found in the temple, Kings reports that the king's officials take it to the prophet Huldah for a verdict." },
  { title: "Miriam's Song", fact: "Exodus preserves a short song attributed to Miriam at the sea, one of the oldest-sounding poems in the Hebrew Bible." },
  { title: "Hannah's Prayer", fact: "Hannah's prayer in Samuel anticipates themes of reversal that reappear centuries later in Mary's song in Luke." },
  { title: "Priscilla and Aquila", fact: "Priscilla and Aquila appear together as a teaching couple in Acts and in Paul's letters, and she is sometimes named first." },
  { title: "Phoebe", fact: "Romans commends Phoebe, describing her with terms of service and patronage, and she is widely thought to have carried the letter." },
  { title: "Lydia of Thyatira", fact: "Acts introduces Lydia as a dealer in purple cloth whose household becomes a base for the mission in Philippi." },
  { title: "Barnabas the Encourager", fact: "Acts glosses the name Barnabas as son of encouragement, and the narrative repeatedly shows him vouching for others." },
  { title: "Timothy's Household", fact: "Second Timothy names Timothy's grandmother and mother, tracing his faith through the women who raised him." },
  { title: "John Mark", fact: "John Mark leaves one mission trip and becomes the subject of a sharp disagreement, yet later letters speak of him warmly." },
  { title: "Onesimus", fact: "Philemon concerns Onesimus, whose name means useful, and Paul plays on that meaning in the letter itself." },
  { title: "Psalms Is Quoted Most", fact: "Among Old Testament books, Psalms and Isaiah are the ones New Testament writers reach for most often." },
  { title: "Psalm 110 in the New Testament", fact: "Psalm 110 is among the most cited Old Testament passages in the New Testament, turning up across Gospels, letters, and Hebrews." },
  { title: "Quoting the Greek", fact: "New Testament writers often quote scripture in wording close to the Greek Septuagint, which is why some quotations differ from the Hebrew." },
  { title: "Echo Without Citation", fact: "Much Old Testament use in the New is allusion rather than quotation. Revelation nearly never cites, and constantly echoes." },
  { title: "It Is Written", fact: "The formula it is written introduces scriptural citation, signaling that the writer is appealing to an already recognized authority." },
  { title: "Fulfillment Language", fact: "Fulfillment in the Gospels can mean more than prediction met. It often means a pattern brought to its intended fullness." },
  { title: "Typology", fact: "Biblical writers read earlier persons and events as patterns anticipating later ones, a way of reading called typology." },
  { title: "Covenant Runs Through", fact: "Covenant links Noah, Abraham, Sinai, David, and the new covenant language of Jeremiah and the New Testament." },
  { title: "The Abrahamic Promise", fact: "The promise to Abraham involves land, descendants, and blessing to all nations, and the third element carries far into the New Testament." },
  { title: "Sinai and Law", fact: "At Sinai a rescued people receives instruction. In the Torah's order, deliverance comes before commandment." },
  { title: "The Davidic Covenant", fact: "Second Samuel promises David an enduring house and throne, and that promise shapes messianic hope for centuries afterward." },
  { title: "A New Covenant", fact: "Jeremiah speaks of a covenant written on hearts, and Hebrews quotes the passage at length to interpret Christ's work." },
  { title: "Parables Are Not Allegories", fact: "Parables usually turn on one central comparison. Pressing every detail for hidden meaning tends to bend the story out of shape." },
  { title: "Parables Provoke", fact: "Many parables end without explanation, leaving hearers to work out where they stand inside the story." },
  { title: "The Good Samaritan", fact: "The good Samaritan story lands harder once a reader knows the tension between Judeans and Samaritans in that period." },
  { title: "Prodigal and Elder", fact: "The parable of the lost son gives the elder brother the final scene, and the father's plea to him ends the story unresolved." },
  { title: "Wisdom Literature", fact: "Job, Proverbs, and Ecclesiastes are often grouped as wisdom books, and they argue with each other as much as they agree." },
  { title: "Proverbs Are Not Promises", fact: "Proverbs offers observations about how life generally goes. Job and Ecclesiastes exist partly to test those generalizations." },
  { title: "Lament Is a Genre", fact: "Lament is a recognized biblical form with its own conventions, and a large share of the Psalms belong to it." },
  { title: "Imprecatory Psalms", fact: "Some psalms call down judgment on enemies in shocking terms. The collection includes rage rather than editing it out." },
  { title: "Psalms of Ascent", fact: "A run of psalms carries the heading song of ascents, often connected with pilgrimage up to Jerusalem." },
  { title: "Royal Psalms", fact: "Some psalms center on the king, and those texts became a major resource for later messianic reflection." },
  { title: "Apocalyptic Style", fact: "Apocalyptic writing uses vision, symbol, and cosmic scale to interpret present crisis. Daniel and Revelation share that toolkit." },
  { title: "Beasts and Empires", fact: "In Daniel's visions, beasts stand for kingdoms. Revelation inherits the convention rather than inventing it." },
  { title: "Prophetic Sign-Acts", fact: "Prophets sometimes acted out their message: buying a field, wearing a yoke, lying on one side. The performance was the sermon." },
  { title: "Oracles Against Nations", fact: "Several prophetic books include long sections addressed to surrounding nations, not only to Israel and Judah." },
  { title: "The Day of the LORD", fact: "The day of the LORD appears across the prophets as a decisive divine intervention, and it is not always good news for Israel." },
  { title: "Remnant", fact: "The prophets repeatedly speak of a remnant, a surviving portion through which the story continues after judgment." },
  { title: "Covenant Lawsuit", fact: "Some prophetic passages are shaped like a legal case, with God bringing charges and creation summoned as witness." },
  { title: "Narrative Repetition", fact: "Biblical narrative repeats scenes with variation: wells, barren mothers, younger sons. The pattern invites comparison." },
  { title: "Younger Brothers", fact: "Isaac, Jacob, Joseph, and David all rise past an older brother's claim. Convention favored the firstborn; these narratives keep looking further down the line." },
  { title: "Barren to Bearing", fact: "Sarah, Rebekah, Rachel, Hannah, and Elizabeth all appear in stories where a barren woman bears a decisive child." },
  { title: "Meals Matter", fact: "Meals mark covenant, welcome, and conflict throughout the Bible, from Abraham's visitors to the Last Supper to Acts." },
  { title: "Hospitality to Strangers", fact: "Hospitality to strangers is a persistent biblical obligation, and Hebrews connects it to entertaining angels unawares." },
  { title: "Care for the Vulnerable", fact: "The widow, the orphan, and the foreigner form a recurring triad in the Torah and the Prophets, naming who the law protects." },
  { title: "Mishpat and Tsedaqah", fact: "Two Hebrew words often paired and translated justice and righteousness form a hendiadys close to social right-dealing." },
  { title: "Hesed", fact: "Hesed is a Hebrew term for loyal, covenantal love. English needs several words for it: steadfast love, mercy, kindness." },
  { title: "Shalom Is More Than Peace", fact: "Shalom reaches past the absence of conflict toward wholeness, soundness, and flourishing." },
  { title: "Glory and Weight", fact: "The Hebrew word for glory carries a root sense of weight or heaviness, so glory implies substance and significance." },
  { title: "Holy Means Set Apart", fact: "The core sense of holiness in the Hebrew Bible is being set apart or distinct, which is why the term applies to times and objects too." },
  { title: "Spirit, Breath, Wind", fact: "One Hebrew word covers spirit, breath, and wind, and Greek has the same range. Translators must choose, and something is always left behind." },
  { title: "Heart Means More", fact: "In biblical usage the heart is the seat of thought and will, not only of feeling. Decisions are made there." },
  { title: "Soul as Whole Life", fact: "The Hebrew word often rendered soul frequently means the living self or life itself rather than an immaterial part." },
  { title: "Flesh in Paul", fact: "Paul often uses flesh for a whole orientation of life rather than for the physical body. Context decides which sense is in play." },
  { title: "Faith and Faithfulness", fact: "One Greek word covers faith, trust, and faithfulness, so some famous phrases can be read in more than one direction." },
  { title: "Grace and Gift", fact: "The Greek word for grace belongs to a family of gift language, and Paul's arguments lean on that everyday sense of generosity." },
  { title: "Repentance Means Turning", fact: "The Greek word behind repentance carries the sense of a changed mind, and the Hebrew equivalent pictures turning around." },
  { title: "One Word, Two Englishes", fact: "In Greek a single word family covers righteousness and justice, so English translations must split what the original held together." },
  { title: "Salvation Means Rescue", fact: "The word groups behind salvation include being rescued, healed, and made whole. Physical deliverance is inside the vocabulary." },
  { title: "Redemption and the Market", fact: "Redemption language draws on buying back, whether property, a relative, or a person. It is commercial imagery pressed into theology." },
  { title: "Atonement's Covering", fact: "Hebrew atonement vocabulary carries a sense of covering or wiping clean, and Leviticus works out the ritual grammar of it." },
  { title: "Sacrifice Was Public", fact: "Israel's sacrifices were public, communal, and often eaten. Many were shared meals rather than pure destruction." },
  { title: "Deuterocanonical Books", fact: "Catholic and Orthodox Bibles include books that Protestant Bibles set aside or place in a separate section. The canon lists differ." },
  { title: "The Ethiopian Canon", fact: "Ethiopian Orthodox tradition recognizes a notably broader canon than any other historic Christian tradition, counting books the others set aside." },
  { title: "Apocrypha Means Hidden", fact: "Apocrypha comes from a Greek word for hidden. As a label it says more about later categorization than about the books themselves." },
  { title: "Longer Esther and Daniel", fact: "Some traditions include additional material in Esther and Daniel that is not present in the Hebrew text." },
  { title: "Canon Took Time", fact: "Recognition of the biblical books unfolded over a long period through use, debate, and consensus rather than a single decisive vote." },
  { title: "Disputed Books", fact: "Some New Testament books, including Hebrews, James, Second Peter, and Revelation, were more debated in early centuries than others." },
  { title: "Reading Aloud Was Normal", fact: "In the ancient world reading was often done aloud, so the sound and rhythm of a text mattered to how it landed." },
  { title: "Deuteronomy Is a Speech", fact: "Most of Deuteronomy is Moses addressing Israel directly. The book reads as a farewell address rather than as narration." },
  { title: "Memory as Manuscript", fact: "Communities carried scripture in memory as well as on scrolls. For most people through most of history, memory was the more available copy." },
  { title: "Lectionary Reading", fact: "Both Jewish and Christian traditions developed cycles for reading scripture publicly, so a calendar shapes what gets heard when." },
  { title: "Haftarah", fact: "Jewish synagogue practice pairs a Torah reading with one from the Prophets. How fixed that cycle already was in the first century is uncertain." },
  { title: "The Bible Names Lost Books", fact: "The Old Testament refers to writings we no longer have, such as the Book of Jashar. The library once had more shelves." },
  { title: "Paul Quotes Poets", fact: "In Acts and in his letters, Paul quotes Greek writers. Scripture's authors were not sealed off from the literature around them." },
  { title: "Uncertain Places", fact: "Some biblical sites are securely identified and others are educated guesses. A confident dot on a Bible map can hide a real debate." },
  { title: "The Bible Argues With Itself", fact: "Job disputes easy wisdom, Ecclesiastes questions gain, and the Psalms shout at God. The canon keeps the arguments rather than smoothing them." },
];
