import type { BibleSkyFact } from "./types";

export const BIBLE_SKY_FACTS: BibleSkyFact[] = [
  { title: "Three Languages", fact: "Most of the Old Testament is Hebrew, parts of Ezra and Daniel are Aramaic, and the New Testament is Greek. The Bible is multilingual from the start." },
  { title: "Late Coordinates", fact: "Chapter numbers and verse numbers were added long after the biblical books were written. They are more like map coordinates than part of the original text." },
  { title: "Chronicles Last", fact: "In many Jewish orders of the Hebrew Bible, Chronicles comes at the end. That gives the canon a very different final note than Malachi." },
  { title: "The Same OT, Different Shelves", fact: "The Hebrew Bible and Protestant Old Testament contain the same books, but they arrange them differently: Torah, Prophets, and Writings versus Law, History, Poetry, and Prophets." },
  { title: "The Twelve", fact: "Hosea through Malachi are often counted as one scroll-sized collection: the Book of the Twelve. Twelve voices, one prophetic shelf." },
  { title: "Scroll Logistics", fact: "Samuel, Kings, Chronicles, and Ezra-Nehemiah were each originally treated as single works. Our 1 and 2 divisions are partly a scroll-and-bookmaking story." },
  { title: "A Five-Book Hymnal", fact: "Psalms is not just one long playlist. It is arranged as five smaller books, each ending with a doxology." },
  { title: "Jeremiah Is Huge", fact: "By word count in many arrangements, Jeremiah is one of the biggest books in the Bible. The prophet had a lot to say and a hard century to say it in." },
  { title: "The Torah Is Massive", fact: "If the Torah is treated as one five-part work, it outweighs every other biblical book by a lot. Genesis through Deuteronomy is the Bible's great foundation slab." },
  { title: "Job Is Set Abroad", fact: "Job is not set in Jerusalem, Judah, or Israel. Its story opens in Uz, giving the book an intentionally borderland feel." },
  { title: "Job's Friends Sit Silent", fact: "Before any arguments begin, Job's friends sit with him seven days and seven nights without speaking. The silence is one of the wisest things they do." },
  { title: "Esther's Hiddenness", fact: "Esther never directly names God, yet the story is built around providence, reversal, and rescue happening behind the curtain." },
  { title: "Daniel's Placement", fact: "Daniel appears among the Writings in the Hebrew Bible, not with Isaiah, Jeremiah, Ezekiel, and the Twelve." },
  { title: "Ruth's Other Home", fact: "English Bibles place Ruth after Judges because of its setting, but Jewish ordering can place Ruth among the festival scrolls in the Writings." },
  { title: "Lamentations as a Scroll", fact: "Lamentations is one of the Megillot, the five festival scrolls, which is why OBA treats it as Writings rather than Latter Prophets." },
  { title: "Hebrews Is Anonymous", fact: "Hebrews has been treasured for centuries, but its author is not named in the book. Ancient readers debated the question too." },
  { title: "Luke's Two-Volume Work", fact: "Luke and Acts read like a two-part project: the story of Jesus, then the story of the gospel moving outward from Jerusalem." },
  { title: "A Fourfold Gospel", fact: "The early church did not keep just one Gospel voice. Matthew, Mark, Luke, and John were received together, preserving four angles on Jesus." },
  { title: "Letters Before Libraries", fact: "Paul's letters were written to real communities before they were gathered into a New Testament collection. Romans was not born as chapter six of a printed book." },
  { title: "Shortest OT Book", fact: "Obadiah is tiny, but it lands a sharp prophetic blow against Edom's pride and violence toward Judah." },
  { title: "Shortest NT Letter", fact: "Third John is so short you can read it in about a minute, but it still gives a vivid window into hospitality and church conflict." },
  { title: "Songs Everywhere", fact: "Psalms is the obvious songbook, but songs and victory poems appear across the Bible, from Exodus to Revelation." },
  { title: "Jonah Is Mostly Story", fact: "Jonah is a prophetic book, but it mostly tells a story about a prophet instead of collecting the prophet's sermons." },
  { title: "A Prophet in Exile", fact: "Ezekiel does much of his prophetic work among deported Judeans in Babylon. The book is full of visions from life after catastrophe." },
  { title: "Isaiah's Huge Horizon", fact: "Isaiah stretches from eighth-century Judah to visions of worldwide restoration. Its scale is one reason later biblical writers return to it so often." },
  { title: "The Shema", fact: "Deuteronomy 6:4 begins the Shema, one of the central confessions of Jewish prayer and memory." },
  { title: "Torah Means Teaching", fact: "Torah is often translated law, but instruction or teaching catches an important part of the word's range." },
  { title: "Former Prophets", fact: "Joshua, Judges, Samuel, and Kings are called Former Prophets because they interpret Israel's history through covenant and prophetic theology." },
  { title: "Latter Prophets", fact: "The Latter Prophets are Isaiah, Jeremiah, Ezekiel, and the Twelve. Daniel is not placed there in the Hebrew Bible." },
  { title: "Ezra-Nehemiah", fact: "Ezra and Nehemiah were often handled as one work, telling a combined return-from-exile and restoration story." },
  { title: "Revelation's Genre Mix", fact: "Revelation is apocalypse, prophecy, and letter all at once. It is addressed to seven churches but thinks on a cosmic scale." },
  { title: "The Bible Is Not Linear", fact: "The Bible is a library, not a single timeline. Narrative, poetry, law, wisdom, prophecy, gospel, apocalypse, and letters sit side by side." },
  { title: "Manuscript Reality", fact: "We do not have the original biblical manuscripts. What we have is an ancient manuscript tradition of copies, translations, and carefully preserved witnesses." },
  { title: "Canon Memory", fact: "By the first century, Jewish sources already show a strong sense of a recognized Scripture collection, often described in three parts." },
  { title: "Paul's Smallest Letter", fact: "Philemon is personal, brief, and explosive: a tiny letter that presses the gospel into the social world of slavery, debt, and reconciliation." },
  { title: "James Gives Commands", fact: "James is famously direct. Its wisdom style is packed with imperatives about speech, wealth, patience, prayer, and practice." },
  { title: "The Ending of Kings", fact: "Kings ends with Jerusalem ruined, but also with a small note of hope: Jehoiachin is released from prison and given a seat at the table." },
  { title: "A Genealogy Surprise", fact: "Matthew's genealogy names women with complicated, outsider, or scandal-shadowed stories, preparing readers for a Messiah who gathers unlikely people." },
  { title: "Mark Moves Fast", fact: "Mark's Gospel loves urgency. Its favorite pace is immediately: scene after scene presses forward toward the cross." },
  { title: "John Counts Signs", fact: "John organizes much of Jesus' public ministry around signs that reveal who he is, then slows dramatically for the final night and crucifixion." },
];
