import type { Metadata } from "next";
import { Crimson_Pro, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson",
});

const siteUrl = "https://www.openbibleassessment.com";
const siteName = "Open Bible Assessment";
const siteDescription =
  "A free, adaptive tool to find out what you actually know about the Bible.";

export const metadata: Metadata = {
  // Required for the relative og/twitter image paths below to be resolved into
  // the absolute URLs that link scrapers demand.
  metadataBase: new URL(siteUrl),
  title: siteName,
  description: siteDescription,
  icons: {
    icon: "/brand/oba-emblem.png",
    apple: "/brand/oba-emblem.png",
  },
  // The share card (Facebook, LinkedIn, Slack, iMessage, WhatsApp, X). The PNG
  // is generated by scripts/generate-og-card.mjs: edit that script, re-run it,
  // and redeploy rather than hand-editing the image.
  openGraph: {
    type: "website",
    url: siteUrl,
    siteName,
    title: siteName,
    description: siteDescription,
    images: [
      {
        url: "/brand/og-card.png",
        width: 1200,
        height: 630,
        alt: "Open Bible Assessment",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteName,
    description: siteDescription,
    images: ["/brand/og-card.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${crimsonPro.variable}`}>{children}</body>
    </html>
  );
}
