-- Generated by scripts/check-frontend-direct-data-access.mjs --write.
-- Verifies that every string-literal relation called through .from("...")
-- by web/app, web/lib, and web/components exists in the public schema.
-- Dynamic .from(...) sites are documented in supabase/review/frontend_direct_data_access.generated.md
-- and intentionally reviewed separately.

do $$
declare
  v_missing jsonb;
begin
  with frontend_relation(name) as (
    values
      ('assessment_answers'),
      ('obs_admin_assessment_readiness'),
      ('obs_admin_coverage_audit'),
      ('obs_admin_difficulty_audit'),
      ('obs_admin_distractor_audit'),
      ('obs_admin_malformed_question_reports'),
      ('obs_admin_question_bank_audit'),
      ('obs_admin_question_bank_audit_summary'),
      ('obs_admin_repetition_audit'),
      ('obs_reading_log_entries'),
      ('obs_starfield_rewards'),
      ('question_reports'),
      ('scripture_books')
  ), live_public_relation as (
    select distinct c.relname as name
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'p', 'v', 'm', 'f')
  )
  select coalesce(jsonb_agg(f.name order by f.name), '[]'::jsonb)
  into v_missing
  from frontend_relation f
  left join live_public_relation live using (name)
  where live.name is null;

  if jsonb_array_length(v_missing) > 0 then
    raise exception 'FAIL: frontend direct relation contract missing relations: %', v_missing;
  end if;
end;
$$;
