-- AUTO-GENERATED DRAFT SEED
begin;

insert into public.people (canonical_name, normalized_key) values
('This', 'this'),
('Then', 'then'),
('When', 'when'),
('Therefore', 'therefore'),
('Now', 'now'),
('What', 'what'),
('Israel', 'israel'),
('There', 'there'),
('Your', 'your'),
('Let', 'let'),
('Jerusalem', 'jerusalem'),
('Spirit', 'spirit'),
('Judah', 'judah'),
('All', 'all'),
('Egypt', 'egypt'),
('One', 'one'),
('Why', 'why'),
('Who', 'who'),
('Moses', 'moses'),
('How', 'how'),
('Jesus', 'jesus'),
('These', 'these'),
('Israelites', 'israelites'),
('Jacob', 'jacob'),
('Because', 'because'),
('David', 'david'),
('Christ', 'christ'),
('King', 'king'),
('Behold', 'behold'),
('Holy', 'holy'),
('Mount', 'mount'),
('That', 'that'),
('Father', 'father'),
('Take', 'take'),
('Surely', 'surely'),
('Abraham', 'abraham'),
('Even', 'even'),
('Come', 'come'),
('Himself', 'himself'),
('Indeed', 'indeed'),
('May', 'may'),
('Look', 'look'),
('LORD''s', 'lord_s'),
('Edom', 'edom'),
('Jordan', 'jordan'),
('Ephraim', 'ephraim'),
('Where', 'where'),
('Since', 'since'),
('Joseph', 'joseph'),
('Moab', 'moab'),
('Benjamin', 'benjamin'),
('Sabbath', 'sabbath'),
('God''s', 'god_s'),
('Law', 'law'),
('Get', 'get'),
('Instead', 'instead'),
('See', 'see'),
('Have', 'have'),
('Isaac', 'isaac'),
('Are', 'are'),
('Thus', 'thus'),
('Each', 'each'),
('Valley', 'valley'),
('Tell', 'tell'),
('Every', 'every'),
('Bring', 'bring'),
('Son', 'son'),
('Book', 'book'),
('While', 'while'),
('Again', 'again'),
('Here', 'here'),
('Some', 'some'),
('Damascus', 'damascus'),
('Although', 'although'),
('Not', 'not'),
('Aaron', 'aaron'),
('Babylon', 'babylon'),
('Ammonites', 'ammonites'),
('Whoever', 'whoever'),
('Sea', 'sea'),
('Remember', 'remember'),
('Hear', 'hear'),
('Can', 'can'),
('Give', 'give'),
('Those', 'those'),
('Yes', 'yes'),
('GOD', 'god'),
('Jews', 'jews'),
('Levites', 'levites'),
('Joshua', 'joshua'),
('Zion', 'zion'),
('Blessed', 'blessed'),
('Will', 'will'),
('Please', 'please'),
('Bethlehem', 'bethlehem'),
('Listen', 'listen'),
('Name', 'name'),
('Gilead', 'gilead'),
('Place', 'place'),
('Sheol', 'sheol'),
('Moreover', 'moreover'),
('Hosts', 'hosts'),
('Pharaoh', 'pharaoh'),
('Philistines', 'philistines'),
('Assyria', 'assyria'),
('Chaldeans', 'chaldeans'),
('Woe', 'woe'),
('Bethel', 'bethel'),
('Otherwise', 'otherwise'),
('Myself', 'myself'),
('Passover', 'passover'),
('Day', 'day'),
('Just', 'just'),
('Today', 'today'),
('Manasseh', 'manasseh'),
('Egyptians', 'egyptians'),
('Eleazar', 'eleazar'),
('Amorites', 'amorites'),
('Though', 'though'),
('Has', 'has'),
('Judea', 'judea'),
('Lebanon', 'lebanon'),
('Most', 'most'),
('Satan', 'satan'),
('Mine', 'mine'),
('Dan', 'dan'),
('Put', 'put'),
('Anyone', 'anyone'),
('Once', 'once'),
('Solomon', 'solomon'),
('Elijah', 'elijah'),
('Samaria', 'samaria'),
('Aram', 'aram'),
('Make', 'make'),
('Like', 'like'),
('Jehoiada', 'jehoiada'),
('Levi', 'levi'),
('Bashan', 'bashan'),
('Hilkiah', 'hilkiah'),
('Seir', 'seir'),
('During', 'during'),
('Sinai', 'sinai'),
('New', 'new'),
('Next', 'next'),
('Only', 'only'),
('Hittites', 'hittites'),
('River', 'river'),
('Consider', 'consider'),
('Gaza', 'gaza'),
('Keep', 'keep'),
('Pray', 'pray'),
('Whenever', 'whenever'),
('Jeroboam', 'jeroboam'),
('Hezekiah', 'hezekiah'),
('Nebuchadnezzar', 'nebuchadnezzar'),
('Daughter', 'daughter'),
('Man', 'man'),
('Baal', 'baal'),
('Canaan', 'canaan'),
('Hebron', 'hebron'),
('Jehoshaphat', 'jehoshaphat'),
('Jericho', 'jericho'),
('Truly', 'truly'),
('Zebulun', 'zebulun'),
('Gad', 'gad'),
('Gath', 'gath'),
('Zechariah', 'zechariah'),
('Feast', 'feast'),
('Galilee', 'galilee'),
('Kings', 'kings'),
('Gibeon', 'gibeon'),
('Mizpah', 'mizpah'),
('Issachar', 'issachar'),
('Simeon', 'simeon'),
('Twelve', 'twelve'),
('Euphrates', 'euphrates'),
('Hebrew', 'hebrew'),
('Savior', 'savior'),
('Scripture', 'scripture'),
('Asher', 'asher'),
('Elam', 'elam'),
('Sidon', 'sidon'),
('About', 'about'),
('Carmel', 'carmel'),
('James', 'james'),
('Meanwhile', 'meanwhile'),
('Nothing', 'nothing'),
('Phinehas', 'phinehas'),
('Should', 'should'),
('Sodom', 'sodom'),
('Among', 'among'),
('However', 'however'),
('Leave', 'leave'),
('Many', 'many'),
('Stand', 'stand'),
('Turn', 'turn'),
('Paul', 'paul'),
('Tent', 'tent'),
('Peter', 'peter'),
('Samuel', 'samuel'),
('Meeting', 'meeting'),
('Jonathan', 'jonathan'),
('Esau', 'esau'),
('John', 'john'),
('Gentiles', 'gentiles'),
('Pilate', 'pilate'),
('Arameans', 'arameans'),
('City', 'city'),
('Shimei', 'shimei'),
('Judas', 'judas'),
('Pharaoh''s', 'pharaoh_s'),
('Sarah', 'sarah'),
('Simon', 'simon'),
('Zadok', 'zadok'),
('Almighty', 'almighty'),
('Maker', 'maker'),
('Men', 'men'),
('Midian', 'midian'),
('Sihon', 'sihon'),
('Wilderness', 'wilderness'),
('Reuben', 'reuben'),
('Speak', 'speak'),
('Arnon', 'arnon'),
('Asherah', 'asherah'),
('Canaanites', 'canaanites'),
('Gilgal', 'gilgal'),
('Heshbon', 'heshbon'),
('Israelite', 'israelite'),
('Its', 'its'),
('Jebusites', 'jebusites'),
('Nathan', 'nathan'),
('Return', 'return'),
('Send', 'send'),
('Abraham''s', 'abraham_s'),
('Benaiah', 'benaiah'),
('Did', 'did'),
('Megiddo', 'megiddo'),
('Perhaps', 'perhaps'),
('Tyre', 'tyre'),
('Whatever', 'whatever'),
('Yourself', 'yourself'),
('First', 'first'),
('Iddo', 'iddo'),
('Nevertheless', 'nevertheless'),
('Open', 'open'),
('Peace', 'peace'),
('Tarshish', 'tarshish'),
('Wait', 'wait'),
('Everyone', 'everyone'),
('Furthermore', 'furthermore'),
('Out', 'out'),
('Rather', 'rather'),
('Show', 'show'),
('Sidonians', 'sidonians'),
('Such', 'such'),
('Three', 'three'),
('Was', 'was'),
('Saul', 'saul'),
('Josiah', 'josiah'),
('David''s', 'david_s'),
('Zedekiah', 'zedekiah'),
('Mary', 'mary'),
('Jehoiakim', 'jehoiakim'),
('Ahaz', 'ahaz'),
('Caleb', 'caleb'),
('Haran', 'haran'),
('Persia', 'persia'),
('Chronicles', 'chronicles'),
('Eliab', 'eliab'),
('Isaiah', 'isaiah'),
('Jehoash', 'jehoash'),
('Joash', 'joash'),
('Merari', 'merari'),
('Naphtali', 'naphtali'),
('Aaron''s', 'aaron_s'),
('Gate', 'gate'),
('Gibeah', 'gibeah'),
('High', 'high'),
('Jewish', 'jewish'),
('Nadab', 'nadab'),
('Nun', 'nun'),
('Asaph', 'asaph'),
('Does', 'does'),
('Nile', 'nile'),
('Red', 'red'),
('Amalekites', 'amalekites'),
('Ashdod', 'ashdod'),
('Azariah', 'azariah'),
('Elah', 'elah'),
('Herod', 'herod'),
('Jephunneh', 'jephunneh'),
('Redeemer', 'redeemer'),
('Sabbaths', 'sabbaths'),
('Say', 'say'),
('Teacher', 'teacher'),
('Ahijah', 'ahijah'),
('Everything', 'everything'),
('Jezreel', 'jezreel'),
('Levite', 'levite'),
('Maacah', 'maacah'),
('Shemaiah', 'shemaiah'),
('Tamar', 'tamar'),
('Against', 'against'),
('Amorite', 'amorite'),
('Arise', 'arise'),
('Ask', 'ask'),
('Beersheba', 'beersheba'),
('Beloved', 'beloved'),
('Bread', 'bread'),
('Edomites', 'edomites'),
('Greetings', 'greetings'),
('Jew', 'jew'),
('Kenaz', 'kenaz'),
('Likewise', 'likewise'),
('Micaiah', 'micaiah'),
('Moabites', 'moabites'),
('Ramah', 'ramah'),
('Rejoice', 'rejoice'),
('Sir', 'sir'),
('Throughout', 'throughout'),
('Unleavened', 'unleavened'),
('Unless', 'unless'),
('Zerubbabel', 'zerubbabel'),
('Afterward', 'afterward'),
('Aroer', 'aroer'),
('Ascent', 'ascent'),
('Cyprus', 'cyprus'),
('Finally', 'finally'),
('Gaius', 'gaius'),
('Great', 'great'),
('Israel''s', 'israel_s'),
('Lachish', 'lachish'),
('Later', 'later'),
('Love', 'love'),
('Master', 'master'),
('Moons', 'moons'),
('Nebo', 'nebo'),
('Neither', 'neither'),
('Rise', 'rise'),
('Teman', 'teman'),
('Timothy', 'timothy'),
('Wherever', 'wherever'),
('Jeremiah', 'jeremiah'),
('Joab', 'joab'),
('Absalom', 'absalom'),
('Ahab', 'ahab'),
('Pharisees', 'pharisees'),
('Balaam', 'balaam'),
('Jehu', 'jehu'),
('Benjamites', 'benjamites'),
('Jehoram', 'jehoram'),
('Philistine', 'philistine'),
('Abner', 'abner'),
('Noah', 'noah'),
('Ahaziah', 'ahaziah'),
('Asa', 'asa'),
('Greeks', 'greeks'),
('Jesse', 'jesse'),
('Lift', 'lift'),
('Meshullam', 'meshullam'),
('Shallum', 'shallum'),
('Uriah', 'uriah'),
('Arabah', 'arabah'),
('Caesar', 'caesar'),
('Philip', 'philip'),
('Reubenites', 'reubenites'),
('Shaphan', 'shaphan'),
('Shechem', 'shechem'),
('Abiathar', 'abiathar'),
('Gadites', 'gadites'),
('Johanan', 'johanan'),
('Kohath', 'kohath'),
('Nebat', 'nebat'),
('Testimony', 'testimony'),
('Cush', 'cush'),
('Cyrus', 'cyrus'),
('Hadad', 'hadad'),
('Jehoiachin', 'jehoiachin'),
('Kadesh', 'kadesh'),
('THE', 'the'),
('Zeruiah', 'zeruiah'),
('Achaia', 'achaia'),
('Asahel', 'asahel'),
('Cursed', 'cursed'),
('Ekron', 'ekron'),
('Eliakim', 'eliakim'),
('Hittite', 'hittite'),
('Horeb', 'horeb'),
('Jehiel', 'jehiel'),
('John''s', 'john_s'),
('Kedesh', 'kedesh'),
('Lord''s', 'lord_s'),
('Mattaniah', 'mattaniah'),
('Obadiah', 'obadiah'),
('Othniel', 'othniel'),
('Prophets', 'prophets'),
('Sanhedrin', 'sanhedrin'),
('Virgin', 'virgin'),
('Which', 'which'),
('Abihu', 'abihu'),
('Abijah', 'abijah'),
('Abiram', 'abiram'),
('Adam', 'adam'),
('Alas', 'alas'),
('Caiaphas', 'caiaphas'),
('Concerning', 'concerning'),
('Could', 'could'),
('Crucify', 'crucify'),
('Dathan', 'dathan'),
('Early', 'early'),
('Geba', 'geba'),
('Hebrews', 'hebrews'),
('Jotham', 'jotham'),
('Kidron', 'kidron'),
('Kiriath-jearim', 'kiriath_jearim'),
('Kohathites', 'kohathites'),
('Korah', 'korah'),
('Long', 'long'),
('Media', 'media'),
('Michael', 'michael'),
('Michmash', 'michmash'),
('Miriam', 'miriam'),
('Negev', 'negev'),
('Never', 'never'),
('People', 'people'),
('Rahab', 'rahab'),
('Rimmon', 'rimmon'),
('Rock', 'rock'),
('Sheba', 'sheba'),
('Stop', 'stop'),
('Tabor', 'tabor'),
('Very', 'very'),
('Wail', 'wail'),
('Watch', 'watch'),
('Whom', 'whom'),
('Zerah', 'zerah'),
('Achbor', 'achbor'),
('Additionally', 'additionally'),
('Akkub', 'akkub'),
('Along', 'along'),
('Ammonite', 'ammonite'),
('Amon', 'amon'),
('Amram', 'amram'),
('Anything', 'anything'),
('Aphek', 'aphek'),
('Beeroth', 'beeroth'),
('Bela', 'bela'),
('Benjamite', 'benjamite'),
('Beor', 'beor'),
('Beth-horon', 'beth_horon'),
('Both', 'both'),
('Brook', 'brook'),
('Call', 'call'),
('Chemosh', 'chemosh'),
('Choose', 'choose'),
('Consequently', 'consequently'),
('Cushites', 'cushites'),
('Delaiah', 'delaiah'),
('Desert', 'desert'),
('Dibon', 'dibon'),
('Drink', 'drink'),
('Field', 'field'),
('Follow', 'follow'),
('Gershon', 'gershon'),
('Gomer', 'gomer'),
('Gozan', 'gozan'),
('Guard', 'guard'),
('Hades', 'hades'),
('Hail', 'hail'),
('Hezron', 'hezron'),
('Hivites', 'hivites'),
('Honor', 'honor'),
('Hormah', 'hormah'),
('Hoshea', 'hoshea'),
('Iscariot', 'iscariot'),
('Isn''t', 'isn_t'),
('JEWS', 'jews'),
('Joab''s', 'joab_s'),
('Jonah', 'jonah'),
('Judge', 'judge'),
('Kenites', 'kenites'),
('KING', 'king'),
('Know', 'know'),
('Levitical', 'levitical'),
('Lower', 'lower'),
('Magog', 'magog'),
('Medeba', 'medeba'),
('Molech', 'molech'),
('Moon', 'moon'),
('Ner', 'ner'),
('Offer', 'offer'),
('Peter''s', 'peter_s'),
('Prepare', 'prepare'),
('Rabbi', 'rabbi'),
('Rephaim', 'rephaim'),
('Righteous', 'righteous'),
('Righteousness', 'righteousness'),
('Scriptures', 'scriptures'),
('Seek', 'seek'),
('Seraiah', 'seraiah'),
('Set', 'set'),
('Shall', 'shall'),
('Shammah', 'shammah'),
('Shealtiel', 'shealtiel'),
('Skull', 'skull'),
('Soon', 'soon'),
('Stay', 'stay'),
('Succoth', 'succoth'),
('Suddenly', 'suddenly'),
('Summon', 'summon'),
('Taanach', 'taanach'),
('Tabernacles', 'tabernacles'),
('Talmon', 'talmon'),
('Teach', 'teach'),
('Timnah', 'timnah'),
('Upper', 'upper'),
('Uzziah', 'uzziah'),
('Uzziel', 'uzziel'),
('Within', 'within'),
('Would', 'would'),
('Ziklag', 'ziklag'),
('Ziph', 'ziph'),
('Selah', 'selah'),
('Elisha', 'elisha'),
('Abram', 'abram'),
('Gideon', 'gideon'),
('Balak', 'balak'),
('Joseph''s', 'joseph_s'),
('Samson', 'samson'),
('Saul''s', 'saul_s'),
('Joram', 'joram'),
('Lot', 'lot'),
('Ezra', 'ezra'),
('Susa', 'susa'),
('Abimelech', 'abimelech'),
('Amaziah', 'amaziah'),
('Baasha', 'baasha'),
('Ishmael', 'ishmael'),
('Jehoahaz', 'jehoahaz'),
('Queen', 'queen'),
('Rachel', 'rachel'),
('Rehoboam', 'rehoboam'),
('Boaz', 'boaz'),
('Brothers', 'brothers'),
('Hiram', 'hiram'),
('Jedaiah', 'jedaiah'),
('Jephthah', 'jephthah'),
('Leah', 'leah'),
('Nabal', 'nabal'),
('Obed-edom', 'obed_edom'),
('Sing', 'sing'),
('Ahikam', 'ahikam'),
('Ben-hadad', 'ben_hadad'),
('Beth-shemesh', 'beth_shemesh'),
('Better', 'better'),
('Greet', 'greet'),
('Pit', 'pit'),
('Whereas', 'whereas'),
('Abigail', 'abigail'),
('Athaliah', 'athaliah'),
('Barnabas', 'barnabas'),
('Cushite', 'cushite'),
('Debir', 'debir'),
('Egyptian', 'egyptian'),
('Jeiel', 'jeiel'),
('Macedonia', 'macedonia'),
('Nineveh', 'nineveh'),
('Omri', 'omri'),
('Raise', 'raise'),
('Terah', 'terah'),
('Ahimelech', 'ahimelech'),
('Ahitub', 'ahitub'),
('Amalek', 'amalek'),
('Amariah', 'amariah'),
('Andrew', 'andrew'),
('Aramean', 'aramean'),
('Asa''s', 'asa_s'),
('Baals', 'baals'),
('Bahurim', 'bahurim'),
('Bani', 'bani'),
('Barak', 'barak'),
('Barzillai', 'barzillai'),
('Bilhah', 'bilhah'),
('Danites', 'danites'),
('Eliashib', 'eliashib'),
('Eliphaz', 'eliphaz'),
('Ephesus', 'ephesus'),
('Gershonites', 'gershonites'),
('Hadadezer', 'hadadezer'),
('Haggai', 'haggai'),
('Helez', 'helez'),
('Hur', 'hur'),
('Immediately', 'immediately'),
('Jeshua', 'jeshua'),
('Jobab', 'jobab'),
('Magdalene', 'magdalene'),
('Mahanaim', 'mahanaim'),
('Mahli', 'mahli'),
('Meraioth', 'meraioth'),
('Nahor', 'nahor'),
('Nazareth', 'nazareth'),
('Neco', 'neco'),
('Nethaniah', 'nethaniah'),
('None', 'none'),
('Perez', 'perez'),
('Praise', 'praise'),
('Rabbah', 'rabbah'),
('Sennacherib', 'sennacherib'),
('Shelomith', 'shelomith'),
('Tobiah', 'tobiah'),
('Topheth', 'topheth'),
('Uzzi', 'uzzi'),
('Wisdom', 'wisdom'),
('Zaccur', 'zaccur'),
('Abarim', 'abarim'),
('Abel', 'abel'),
('Abiezer', 'abiezer'),
('Abishai', 'abishai'),
('Aha', 'aha'),
('Ahohite', 'ahohite'),
('Anakim', 'anakim'),
('Anathoth', 'anathoth'),
('Anathothite', 'anathothite'),
('Bilhan', 'bilhan'),
('Dagon', 'dagon'),
('Ezem', 'ezem'),
('Ezer', 'ezer'),
('Far', 'far'),
('Gera', 'gera'),
('Gershom', 'gershom'),
('Going', 'going'),
('Goshen', 'goshen'),
('Greek', 'greek'),
('Hadoram', 'hadoram'),
('Hagar', 'hagar'),
('Hamath', 'hamath'),
('Hanan', 'hanan'),
('Hashabiah', 'hashabiah'),
('Hazael', 'hazael'),
('Jamin', 'jamin'),
('Jeconiah', 'jeconiah'),
('Jeush', 'jeush'),
('Jezreelite', 'jezreelite'),
('Joel', 'joel'),
('Keilah', 'keilah'),
('Kibroth-hattaavah', 'kibroth_hattaavah'),
('Kish', 'kish'),
('Leviathan', 'leviathan'),
('Marah', 'marah'),
('Mareshah', 'mareshah'),
('Mattithiah', 'mattithiah'),
('Melchizedek', 'melchizedek'),
('Midianites', 'midianites'),
('Mushi', 'mushi'),
('Naboth', 'naboth'),
('Nations', 'nations'),
('Paran', 'paran'),
('Pekah', 'pekah'),
('Pisgah', 'pisgah'),
('Ram', 'ram'),
('Rapha', 'rapha'),
('Rescue', 'rescue'),
('Reuel', 'reuel'),
('Rome', 'rome'),
('Servant', 'servant'),
('Shaul', 'shaul'),
('Shelah', 'shelah'),
('Shur', 'shur'),
('South', 'south'),
('Still', 'still'),
('Tola', 'tola'),
('Tomorrow', 'tomorrow'),
('Weeks', 'weeks'),
('Worship', 'worship'),
('Year', 'year'),
('Zephaniah', 'zephaniah'),
('Zin', 'zin'),
('Zippor', 'zippor'),
('Zobah', 'zobah'),
('Abaddon', 'abaddon'),
('Abihail', 'abihail'),
('Abinadab', 'abinadab'),
('Above', 'above'),
('Accompanied', 'accompanied'),
('According', 'according'),
('Achor', 'achor'),
('Adaiah', 'adaiah'),
('Adullam', 'adullam'),
('Ahilud', 'ahilud'),
('Ahiman', 'ahiman'),
('Ahinoam', 'ahinoam'),
('Akrabbim', 'akrabbim'),
('Also', 'also'),
('Always', 'always'),
('Ammiel', 'ammiel'),
('Amoz', 'amoz'),
('Annas', 'annas'),
('Answer', 'answer'),
('Apollos', 'apollos'),
('Arad', 'arad'),
('Aren''t', 'aren_t'),
('Aristarchus', 'aristarchus'),
('Asaiah', 'asaiah'),
('Ashan', 'ashan'),
('Ashkelon', 'ashkelon'),
('Asshur', 'asshur'),
('Ataroth', 'ataroth'),
('Ater', 'ater'),
('Avoid', 'avoid'),
('Avvim', 'avvim'),
('Awake', 'awake'),
('Azaziah', 'azaziah'),
('Azgad', 'azgad'),
('Baal-zephon', 'baal_zephon'),
('Barabbas', 'barabbas'),
('Beelzebul', 'beelzebul'),
('Ben-hinnom', 'ben_hinnom'),
('Beth-shan', 'beth_shan'),
('Bethany', 'bethany'),
('Caesar''s', 'caesar_s'),
('Caleb''s', 'caleb_s'),
('Canaanite', 'canaanite'),
('Carry', 'carry'),
('Chaldean', 'chaldean'),
('Chenaanah', 'chenaanah'),
('Child', 'child'),
('Children', 'children'),
('Command', 'command'),
('Confessing', 'confessing'),
('Covenant', 'covenant'),
('Creator', 'creator'),
('Crispus', 'crispus'),
('Daberath', 'daberath'),
('Death', 'death'),
('Decapolis', 'decapolis'),
('Declare', 'declare'),
('Dedan', 'dedan'),
('Demas', 'demas'),
('Despite', 'despite'),
('Destroy', 'destroy'),
('Dishan', 'dishan'),
('Dishon', 'dishon'),
('Dodo', 'dodo'),
('Draw', 'draw'),
('Drive', 'drive'),
('Dumah', 'dumah'),
('Eastern', 'eastern'),
('Ebal', 'ebal'),
('Eden', 'eden'),
('Edrei', 'edrei'),
('Elihu', 'elihu'),
('Eliphelet', 'eliphelet'),
('Ephrath', 'ephrath'),
('Ephrathah', 'ephrathah'),
('Eshcol', 'eshcol'),
('Etham', 'etham'),
('Eve', 'eve'),
('Ezion-geber', 'ezion_geber'),
('Fall', 'fall'),
('Fallen', 'fallen'),
('Fathers', 'fathers'),
('Fear', 'fear'),
('Fight', 'fight'),
('Galatia', 'galatia'),
('Giddel', 'giddel'),
('Gilboa', 'gilboa'),
('Gileadite', 'gileadite'),
('Gittaim', 'gittaim'),
('Gittite', 'gittite'),
('Golgotha', 'golgotha'),
('Gomorrah', 'gomorrah'),
('Good', 'good'),
('Grace', 'grace'),
('Greece', 'greece'),
('Habor', 'habor'),
('Hakkoz', 'hakkoz'),
('Halah', 'halah'),
('Hananiah', 'hananiah'),
('Harim', 'harim'),
('Harness', 'harness'),
('Hazor', 'hazor'),
('Heal', 'heal'),
('Heaven', 'heaven'),
('Heldai', 'heldai'),
('Hermon', 'hermon'),
('Hide', 'hide'),
('Hosanna', 'hosanna'),
('Hushathite', 'hushathite'),
('Ikkesh', 'ikkesh'),
('Increase', 'increase'),
('Instruct', 'instruct'),
('Ira', 'ira'),
('Izhar', 'izhar'),
('Izharites', 'izharites'),
('Jabesh', 'jabesh'),
('Jahaz', 'jahaz'),
('Jairus', 'jairus'),
('Jeremoth', 'jeremoth'),
('Jerimoth', 'jerimoth'),
('Jeroboam''s', 'jeroboam_s'),
('Jeshaiah', 'jeshaiah'),
('Jeshurun', 'jeshurun'),
('Jezebel', 'jezebel'),
('Joktan', 'joktan'),
('Kedar', 'kedar'),
('Kiriath-sepher', 'kiriath_sepher'),
('Kiriathaim', 'kiriathaim'),
('Kishon', 'kishon'),
('Knowing', 'knowing'),
('Kohathite', 'kohathite'),
('Korahites', 'korahites'),
('Land', 'land'),
('Launderer''s', 'launderer_s'),
('Libnah', 'libnah'),
('Libyans', 'libyans'),
('Life', 'life'),
('Little', 'little'),
('Lod', 'lod'),
('Lotan', 'lotan'),
('Luz', 'luz'),
('Maaseiah', 'maaseiah'),
('Machir', 'machir'),
('Malchijah', 'malchijah'),
('Malluch', 'malluch'),
('Mark', 'mark'),
('Mattenai', 'mattenai'),
('Medes', 'medes'),
('Merarite', 'merarite'),
('Michal', 'michal'),
('Migdol', 'migdol'),
('Mighty', 'mighty'),
('Milcom', 'milcom'),
('Moriah', 'moriah'),
('Naamah', 'naamah'),
('Nahath', 'nahath'),
('Netophathite', 'netophathite'),
('Nimrod', 'nimrod'),
('Oak', 'oak'),
('Ono', 'ono'),
('Ophir', 'ophir'),
('Others', 'others'),
('Outside', 'outside'),
('Panic', 'panic'),
('Pas-dammim', 'pas_dammim'),
('Pashhur', 'pashhur'),
('Pay', 'pay'),
('Pedaiah', 'pedaiah'),
('Penuel', 'penuel'),
('Perizzites', 'perizzites'),
('Pi-hahiroth', 'pi_hahiroth'),
('Pick', 'pick'),
('Plague', 'plague'),
('Present', 'present'),
('Prophecy', 'prophecy'),
('Prophet', 'prophet'),
('Purify', 'purify'),
('Reaiah', 'reaiah'),
('Rechab', 'rechab'),
('Remaliah', 'remaliah'),
('Remove', 'remove'),
('Right', 'right'),
('Roll', 'roll'),
('Run', 'run'),
('Save', 'save'),
('Senir', 'senir'),
('Serve', 'serve'),
('Seven', 'seven'),
('Shem', 'shem'),
('Shephatiah', 'shephatiah'),
('Shepherd', 'shepherd'),
('Shiloh', 'shiloh'),
('Shout', 'shout'),
('Shunammite', 'shunammite'),
('Solomon''s', 'solomon_s'),
('Strength', 'strength'),
('Submit', 'submit'),
('Tahpanhes', 'tahpanhes'),
('Talmai', 'talmai'),
('Tekoa', 'tekoa'),
('Tekoite', 'tekoite'),
('Test', 'test'),
('Theophilus', 'theophilus'),
('Thessalonica', 'thessalonica'),
('Throw', 'throw'),
('Tiglath-pileser', 'tiglath_pileser'),
('Titus', 'titus'),
('Trust', 'trust'),
('Truth', 'truth'),
('Unni', 'unni'),
('Uri', 'uri'),
('Walk', 'walk'),
('Western', 'western'),
('Witness', 'witness'),
('Work', 'work'),
('Write', 'write'),
('Zabad', 'zabad'),
('Zedekiah''s', 'zedekiah_s'),
('Zemaraim', 'zemaraim'),
('Daniel', 'daniel'),
('Esther', 'esther'),
('Baruch', 'baruch'),
('Lamb', 'lamb'),
('Mordecai', 'mordecai'),
('Haman', 'haman'),
('Job', 'job'),
('Eli', 'eli'),
('Naomi', 'naomi'),
('Laban', 'laban'),
('Festus', 'festus'),
('Xerxes', 'xerxes'),
('Achish', 'achish'),
('Adonijah', 'adonijah'),
('Darius', 'darius'),
('Gedaliah', 'gedaliah'),
('Gehazi', 'gehazi'),
('Goliath', 'goliath'),
('Neriah', 'neriah'),
('Rebekah', 'rebekah'),
('Ruth', 'ruth'),
('Abednego', 'abednego'),
('Antioch', 'antioch'),
('Cain', 'cain'),
('Kareah', 'kareah'),
('Mephibosheth', 'mephibosheth'),
('Meshach', 'meshach'),
('Naaman', 'naaman'),
('Nicodemus', 'nicodemus'),
('Shadrach', 'shadrach'),
('Silas', 'silas'),
('Ahimaaz', 'ahimaaz'),
('Ahithophel', 'ahithophel'),
('Ananias', 'ananias'),
('Artaxerxes', 'artaxerxes'),
('Bless', 'bless'),
('Deborah', 'deborah'),
('Glory', 'glory'),
('Hallelujah', 'hallelujah'),
('Hamor', 'hamor'),
('Obed', 'obed'),
('Roman', 'roman'),
('Stephen', 'stephen'),
('Zimri', 'zimri'),
('Agrippa', 'agrippa'),
('Amos', 'amos'),
('Any', 'any'),
('Arphaxad', 'arphaxad'),
('Artemis', 'artemis'),
('Assyrians', 'assyrians'),
('Basemath', 'basemath'),
('Bezalel', 'bezalel'),
('Caesarea', 'caesarea'),
('Cry', 'cry'),
('Cut', 'cut'),
('Delilah', 'delilah'),
('Ebiasaph', 'ebiasaph'),
('Elkanah', 'elkanah'),
('Enoch', 'enoch'),
('Ephron', 'ephron'),
('Gaal', 'gaal'),
('Hagrites', 'hagrites'),
('Haman''s', 'haman_s'),
('Hegai', 'hegai'),
('Helon', 'helon'),
('Include', 'include'),
('Ish-bosheth', 'ish_bosheth'),
('Jediael', 'jediael'),
('Jerahmeel', 'jerahmeel'),
('Jubilee', 'jubilee'),
('Light', 'light'),
('Paul''s', 'paul_s'),
('Pur', 'pur'),
('Shobal', 'shobal'),
('Tirzah', 'tirzah'),
('Troas', 'troas'),
('Word', 'word'),
('Zebadiah', 'zebadiah'),
('Ziba', 'ziba'),
('Zichri', 'zichri'),
('Zohar', 'zohar'),
('Abdon', 'abdon'),
('Abidan', 'abidan'),
('Abinoam', 'abinoam'),
('Abiud', 'abiud'),
('Abyss', 'abyss'),
('Achan', 'achan'),
('Achshaph', 'achshaph'),
('Acsah', 'acsah'),
('Adar', 'adar'),
('Almon-diblathaim', 'almon_diblathaim'),
('Ammon', 'ammon'),
('Amnon', 'amnon'),
('Ariel', 'ariel'),
('Arvad', 'arvad'),
('Assir', 'assir'),
('Aware', 'aware'),
('Baal-perazim', 'baal_perazim'),
('Baanah', 'baanah'),
('Bakbukiah', 'bakbukiah'),
('Balaam''s', 'balaam_s'),
('Beerothite', 'beerothite'),
('Belonging', 'belonging'),
('Belshazzar', 'belshazzar'),
('Benjamin''s', 'benjamin_s'),
('Beth-jeshimoth', 'beth_jeshimoth'),
('Binnui', 'binnui'),
('Blow', 'blow'),
('Branch', 'branch'),
('Buy', 'buy'),
('Casiphia', 'casiphia'),
('Cilicia', 'cilicia'),
('Construct', 'construct'),
('Corinth', 'corinth'),
('Corinthians', 'corinthians'),
('Cornelius', 'cornelius'),
('Crete', 'crete'),
('Derbe', 'derbe'),
('Dimon', 'dimon'),
('East', 'east'),
('Ebed', 'ebed'),
('Ebed-melech', 'ebed_melech'),
('Ebenezer', 'ebenezer'),
('Eight', 'eight'),
('Elasah', 'elasah'),
('Eliakim''s', 'eliakim_s'),
('Elimelech', 'elimelech'),
('Elizabeth', 'elizabeth'),
('Eloi', 'eloi'),
('Ephlal', 'ephlal'),
('Esau''s', 'esau_s'),
('Ethan', 'ethan'),
('Father''s', 'father_s'),
('Galal', 'galal'),
('Galileans', 'galileans'),
('Gazez', 'gazez'),
('Gemariah', 'gemariah'),
('Genubath', 'genubath'),
('Gershonite', 'gershonite'),
('Gideoni', 'gideoni'),
('Gileadites', 'gileadites'),
('God-fearing', 'god_fearing'),
('Gudgodah', 'gudgodah'),
('Hammedatha', 'hammedatha'),
('Hanamel', 'hanamel'),
('Hannah', 'hannah'),
('Hathach', 'hathach'),
('Henadad', 'henadad'),
('Horesh', 'horesh'),
('Horonaim', 'horonaim'),
('Hosah', 'hosah'),
('Hosea', 'hosea'),
('Hushai', 'hushai'),
('Husham', 'husham'),
('Iconium', 'iconium'),
('Immer', 'immer'),
('Ithamar', 'ithamar'),
('Jabesh-gilead', 'jabesh_gilead'),
('Jahath', 'jahath'),
('Japheth', 'japheth'),
('Japhia', 'japhia'),
('Jared', 'jared'),
('Jeroham', 'jeroham'),
('Joiarib', 'joiarib'),
('Jokshan', 'jokshan'),
('Jonadab', 'jonadab'),
('Josiah''s', 'josiah_s'),
('Kadmiel', 'kadmiel'),
('Kue', 'kue'),
('Laish', 'laish'),
('Large', 'large'),
('Leshem', 'leshem'),
('Lystra', 'lystra'),
('Mahalalel', 'mahalalel'),
('Makkedah', 'makkedah'),
('Manahathites', 'manahathites'),
('Martha', 'martha'),
('Meshelemiah', 'meshelemiah'),
('Micah', 'micah'),
('Micah''s', 'micah_s'),
('Midianite', 'midianite'),
('Moabitess', 'moabitess'),
('Moza', 'moza'),
('Nazirite', 'nazirite'),
('Nebuzaradan', 'nebuzaradan'),
('Nehemiah', 'nehemiah'),
('Netophathites', 'netophathites'),
('Nicolaitans', 'nicolaitans'),
('Observe', 'observe'),
('Oholibamah', 'oholibamah'),
('Olives', 'olives'),
('Overlay', 'overlay'),
('Peninnah', 'peninnah'),
('Philippi', 'philippi'),
('Plunder', 'plunder'),
('Presence', 'presence'),
('Purim', 'purim'),
('Rabshakeh', 'rabshakeh'),
('Rebekah''s', 'rebekah_s'),
('Repay', 'repay'),
('Rephaiah', 'rephaiah'),
('Restore', 'restore'),
('Romans', 'romans'),
('Samaritan', 'samaritan'),
('Sanballat', 'sanballat'),
('Seled', 'seled'),
('Shebna', 'shebna'),
('Shemiramoth', 'shemiramoth'),
('Sheshbazzar', 'sheshbazzar'),
('Shethar-bozenai', 'shethar_bozenai'),
('Shilonite', 'shilonite'),
('Shoot', 'shoot'),
('Sisera', 'sisera'),
('Sismai', 'sismai'),
('Six', 'six'),
('Stephanas', 'stephanas'),
('Syria', 'syria'),
('Tahpenes', 'tahpenes'),
('Tattenai', 'tattenai'),
('Temanite', 'temanite'),
('Terror', 'terror'),
('Tibni', 'tibni'),
('Tobijah', 'tobijah'),
('Treason', 'treason'),
('Tubal-cain', 'tubal_cain'),
('Vashti', 'vashti'),
('Watchman', 'watchman'),
('Zalmunna', 'zalmunna'),
('Zebah', 'zebah'),
('Zerahiah', 'zerahiah'),
('Zilpah', 'zilpah'),
('Zorathites', 'zorathites'),
('Abanah', 'abanah'),
('Abandon', 'abandon'),
('Abba', 'abba'),
('Abdi', 'abdi'),
('Abel-keramim', 'abel_keramim'),
('Abi', 'abi'),
('Abiathar''s', 'abiathar_s'),
('Abimelech''s', 'abimelech_s'),
('Abinadab''s', 'abinadab_s'),
('Abishag', 'abishag'),
('Abishua', 'abishua'),
('Abram''s', 'abram_s'),
('Abstain', 'abstain'),
('Abundant', 'abundant'),
('Acacias', 'acacias'),
('Accept', 'accept'),
('Achaicus', 'achaicus'),
('Act', 'act'),
('Acts', 'acts'),
('Adah', 'adah'),
('Add', 'add'),
('Addar', 'addar'),
('Adiel', 'adiel'),
('Admatha', 'admatha'),
('Administer', 'administer'),
('Adoni-zedek', 'adoni_zedek'),
('Adullamite', 'adullamite'),
('Advocate', 'advocate'),
('Agag', 'agag'),
('Agagite', 'agagite'),
('Agee', 'agee'),
('Ahab''s', 'ahab_s'),
('Ahasbai', 'ahasbai'),
('Ahava', 'ahava'),
('Aher', 'aher'),
('Ahiezer', 'ahiezer'),
('Ahimoth', 'ahimoth'),
('Ahinadab', 'ahinadab'),
('Ahiram', 'ahiram'),
('Ahiramite', 'ahiramite'),
('Ahishahar', 'ahishahar'),
('Ahithophel''s', 'ahithophel_s'),
('Ahumai', 'ahumai'),
('Aiath', 'aiath'),
('Aijalon', 'aijalon'),
('Aim', 'aim'),
('Ain', 'ain'),
('Akan', 'akan'),
('Alexander', 'alexander'),
('Allow', 'allow'),
('Almodad', 'almodad'),
('Alphaeus', 'alphaeus'),
('Already', 'already'),
('Alush', 'alush'),
('Amalekite', 'amalekite'),
('Amana', 'amana'),
('Amasai', 'amasai'),
('Ammihud', 'ammihud'),
('Amnon''s', 'amnon_s'),
('Amphipolis', 'amphipolis'),
('Amramites', 'amramites'),
('Anab', 'anab'),
('Anah', 'anah'),
('Anaharath', 'anaharath'),
('Anakites', 'anakites'),
('Anan', 'anan'),
('Ananiah', 'ananiah'),
('Ancient', 'ancient'),
('Anem', 'anem'),
('Anguish', 'anguish');

insert into public.people_aliases (person_id, alias, alias_norm, match_strategy)
select
  p.id,
  p.canonical_name,
  lower(p.canonical_name),
  case when position(' ' in p.canonical_name) > 0 then 'phrase' else 'exact' end
from public.people p
where p.normalized_key in (
'this',
'then',
'when',
'therefore',
'now',
'what',
'israel',
'there',
'your',
'let',
'jerusalem',
'spirit',
'judah',
'all',
'egypt',
'one',
'why',
'who',
'moses',
'how',
'jesus',
'these',
'israelites',
'jacob',
'because',
'david',
'christ',
'king',
'behold',
'holy',
'mount',
'that',
'father',
'take',
'surely',
'abraham',
'even',
'come',
'himself',
'indeed',
'may',
'look',
'lord_s',
'edom',
'jordan',
'ephraim',
'where',
'since',
'joseph',
'moab',
'benjamin',
'sabbath',
'god_s',
'law',
'get',
'instead',
'see',
'have',
'isaac',
'are',
'thus',
'each',
'valley',
'tell',
'every',
'bring',
'son',
'book',
'while',
'again',
'here',
'some',
'damascus',
'although',
'not',
'aaron',
'babylon',
'ammonites',
'whoever',
'sea',
'remember',
'hear',
'can',
'give',
'those',
'yes',
'god',
'jews',
'levites',
'joshua',
'zion',
'blessed',
'will',
'please',
'bethlehem',
'listen',
'name',
'gilead',
'place',
'sheol',
'moreover',
'hosts',
'pharaoh',
'philistines',
'assyria',
'chaldeans',
'woe',
'bethel',
'otherwise',
'myself',
'passover',
'day',
'just',
'today',
'manasseh',
'egyptians',
'eleazar',
'amorites',
'though',
'has',
'judea',
'lebanon',
'most',
'satan',
'mine',
'dan',
'put',
'anyone',
'once',
'solomon',
'elijah',
'samaria',
'aram',
'make',
'like',
'jehoiada',
'levi',
'bashan',
'hilkiah',
'seir',
'during',
'sinai',
'new',
'next',
'only',
'hittites',
'river',
'consider',
'gaza',
'keep',
'pray',
'whenever',
'jeroboam',
'hezekiah',
'nebuchadnezzar',
'daughter',
'man',
'baal',
'canaan',
'hebron',
'jehoshaphat',
'jericho',
'truly',
'zebulun',
'gad',
'gath',
'zechariah',
'feast',
'galilee',
'kings',
'gibeon',
'mizpah',
'issachar',
'simeon',
'twelve',
'euphrates',
'hebrew',
'savior',
'scripture',
'asher',
'elam',
'sidon',
'about',
'carmel',
'james',
'meanwhile',
'nothing',
'phinehas',
'should',
'sodom',
'among',
'however',
'leave',
'many',
'stand',
'turn',
'paul',
'tent',
'peter',
'samuel',
'meeting',
'jonathan',
'esau',
'john',
'gentiles',
'pilate',
'arameans',
'city',
'shimei',
'judas',
'pharaoh_s',
'sarah',
'simon',
'zadok',
'almighty',
'maker',
'men',
'midian',
'sihon',
'wilderness',
'reuben',
'speak',
'arnon',
'asherah',
'canaanites',
'gilgal',
'heshbon',
'israelite',
'its',
'jebusites',
'nathan',
'return',
'send',
'abraham_s',
'benaiah',
'did',
'megiddo',
'perhaps',
'tyre',
'whatever',
'yourself',
'first',
'iddo',
'nevertheless',
'open',
'peace',
'tarshish',
'wait',
'everyone',
'furthermore',
'out',
'rather',
'show',
'sidonians',
'such',
'three',
'was',
'saul',
'josiah',
'david_s',
'zedekiah',
'mary',
'jehoiakim',
'ahaz',
'caleb',
'haran',
'persia',
'chronicles',
'eliab',
'isaiah',
'jehoash',
'joash',
'merari',
'naphtali',
'aaron_s',
'gate',
'gibeah',
'high',
'jewish',
'nadab',
'nun',
'asaph',
'does',
'nile',
'red',
'amalekites',
'ashdod',
'azariah',
'elah',
'herod',
'jephunneh',
'redeemer',
'sabbaths',
'say',
'teacher',
'ahijah',
'everything',
'jezreel',
'levite',
'maacah',
'shemaiah',
'tamar',
'against',
'amorite',
'arise',
'ask',
'beersheba',
'beloved',
'bread',
'edomites',
'greetings',
'jew',
'kenaz',
'likewise',
'micaiah',
'moabites',
'ramah',
'rejoice',
'sir',
'throughout',
'unleavened',
'unless',
'zerubbabel',
'afterward',
'aroer',
'ascent',
'cyprus',
'finally',
'gaius',
'great',
'israel_s',
'lachish',
'later',
'love',
'master',
'moons',
'nebo',
'neither',
'rise',
'teman',
'timothy',
'wherever',
'jeremiah',
'joab',
'absalom',
'ahab',
'pharisees',
'balaam',
'jehu',
'benjamites',
'jehoram',
'philistine',
'abner',
'noah',
'ahaziah',
'asa',
'greeks',
'jesse',
'lift',
'meshullam',
'shallum',
'uriah',
'arabah',
'caesar',
'philip',
'reubenites',
'shaphan',
'shechem',
'abiathar',
'gadites',
'johanan',
'kohath',
'nebat',
'testimony',
'cush',
'cyrus',
'hadad',
'jehoiachin',
'kadesh',
'the',
'zeruiah',
'achaia',
'asahel',
'cursed',
'ekron',
'eliakim',
'hittite',
'horeb',
'jehiel',
'john_s',
'kedesh',
'lord_s',
'mattaniah',
'obadiah',
'othniel',
'prophets',
'sanhedrin',
'virgin',
'which',
'abihu',
'abijah',
'abiram',
'adam',
'alas',
'caiaphas',
'concerning',
'could',
'crucify',
'dathan',
'early',
'geba',
'hebrews',
'jotham',
'kidron',
'kiriath_jearim',
'kohathites',
'korah',
'long',
'media',
'michael',
'michmash',
'miriam',
'negev',
'never',
'people',
'rahab',
'rimmon',
'rock',
'sheba',
'stop',
'tabor',
'very',
'wail',
'watch',
'whom',
'zerah',
'achbor',
'additionally',
'akkub',
'along',
'ammonite',
'amon',
'amram',
'anything',
'aphek',
'beeroth',
'bela',
'benjamite',
'beor',
'beth_horon',
'both',
'brook',
'call',
'chemosh',
'choose',
'consequently',
'cushites',
'delaiah',
'desert',
'dibon',
'drink',
'field',
'follow',
'gershon',
'gomer',
'gozan',
'guard',
'hades',
'hail',
'hezron',
'hivites',
'honor',
'hormah',
'hoshea',
'iscariot',
'isn_t',
'jews',
'joab_s',
'jonah',
'judge',
'kenites',
'king',
'know',
'levitical',
'lower',
'magog',
'medeba',
'molech',
'moon',
'ner',
'offer',
'peter_s',
'prepare',
'rabbi',
'rephaim',
'righteous',
'righteousness',
'scriptures',
'seek',
'seraiah',
'set',
'shall',
'shammah',
'shealtiel',
'skull',
'soon',
'stay',
'succoth',
'suddenly',
'summon',
'taanach',
'tabernacles',
'talmon',
'teach',
'timnah',
'upper',
'uzziah',
'uzziel',
'within',
'would',
'ziklag',
'ziph',
'selah',
'elisha',
'abram',
'gideon',
'balak',
'joseph_s',
'samson',
'saul_s',
'joram',
'lot',
'ezra',
'susa',
'abimelech',
'amaziah',
'baasha',
'ishmael',
'jehoahaz',
'queen',
'rachel',
'rehoboam',
'boaz',
'brothers',
'hiram',
'jedaiah',
'jephthah',
'leah',
'nabal',
'obed_edom',
'sing',
'ahikam',
'ben_hadad',
'beth_shemesh',
'better',
'greet',
'pit',
'whereas',
'abigail',
'athaliah',
'barnabas',
'cushite',
'debir',
'egyptian',
'jeiel',
'macedonia',
'nineveh',
'omri',
'raise',
'terah',
'ahimelech',
'ahitub',
'amalek',
'amariah',
'andrew',
'aramean',
'asa_s',
'baals',
'bahurim',
'bani',
'barak',
'barzillai',
'bilhah',
'danites',
'eliashib',
'eliphaz',
'ephesus',
'gershonites',
'hadadezer',
'haggai',
'helez',
'hur',
'immediately',
'jeshua',
'jobab',
'magdalene',
'mahanaim',
'mahli',
'meraioth',
'nahor',
'nazareth',
'neco',
'nethaniah',
'none',
'perez',
'praise',
'rabbah',
'sennacherib',
'shelomith',
'tobiah',
'topheth',
'uzzi',
'wisdom',
'zaccur',
'abarim',
'abel',
'abiezer',
'abishai',
'aha',
'ahohite',
'anakim',
'anathoth',
'anathothite',
'bilhan',
'dagon',
'ezem',
'ezer',
'far',
'gera',
'gershom',
'going',
'goshen',
'greek',
'hadoram',
'hagar',
'hamath',
'hanan',
'hashabiah',
'hazael',
'jamin',
'jeconiah',
'jeush',
'jezreelite',
'joel',
'keilah',
'kibroth_hattaavah',
'kish',
'leviathan',
'marah',
'mareshah',
'mattithiah',
'melchizedek',
'midianites',
'mushi',
'naboth',
'nations',
'paran',
'pekah',
'pisgah',
'ram',
'rapha',
'rescue',
'reuel',
'rome',
'servant',
'shaul',
'shelah',
'shur',
'south',
'still',
'tola',
'tomorrow',
'weeks',
'worship',
'year',
'zephaniah',
'zin',
'zippor',
'zobah',
'abaddon',
'abihail',
'abinadab',
'above',
'accompanied',
'according',
'achor',
'adaiah',
'adullam',
'ahilud',
'ahiman',
'ahinoam',
'akrabbim',
'also',
'always',
'ammiel',
'amoz',
'annas',
'answer',
'apollos',
'arad',
'aren_t',
'aristarchus',
'asaiah',
'ashan',
'ashkelon',
'asshur',
'ataroth',
'ater',
'avoid',
'avvim',
'awake',
'azaziah',
'azgad',
'baal_zephon',
'barabbas',
'beelzebul',
'ben_hinnom',
'beth_shan',
'bethany',
'caesar_s',
'caleb_s',
'canaanite',
'carry',
'chaldean',
'chenaanah',
'child',
'children',
'command',
'confessing',
'covenant',
'creator',
'crispus',
'daberath',
'death',
'decapolis',
'declare',
'dedan',
'demas',
'despite',
'destroy',
'dishan',
'dishon',
'dodo',
'draw',
'drive',
'dumah',
'eastern',
'ebal',
'eden',
'edrei',
'elihu',
'eliphelet',
'ephrath',
'ephrathah',
'eshcol',
'etham',
'eve',
'ezion_geber',
'fall',
'fallen',
'fathers',
'fear',
'fight',
'galatia',
'giddel',
'gilboa',
'gileadite',
'gittaim',
'gittite',
'golgotha',
'gomorrah',
'good',
'grace',
'greece',
'habor',
'hakkoz',
'halah',
'hananiah',
'harim',
'harness',
'hazor',
'heal',
'heaven',
'heldai',
'hermon',
'hide',
'hosanna',
'hushathite',
'ikkesh',
'increase',
'instruct',
'ira',
'izhar',
'izharites',
'jabesh',
'jahaz',
'jairus',
'jeremoth',
'jerimoth',
'jeroboam_s',
'jeshaiah',
'jeshurun',
'jezebel',
'joktan',
'kedar',
'kiriath_sepher',
'kiriathaim',
'kishon',
'knowing',
'kohathite',
'korahites',
'land',
'launderer_s',
'libnah',
'libyans',
'life',
'little',
'lod',
'lotan',
'luz',
'maaseiah',
'machir',
'malchijah',
'malluch',
'mark',
'mattenai',
'medes',
'merarite',
'michal',
'migdol',
'mighty',
'milcom',
'moriah',
'naamah',
'nahath',
'netophathite',
'nimrod',
'oak',
'ono',
'ophir',
'others',
'outside',
'panic',
'pas_dammim',
'pashhur',
'pay',
'pedaiah',
'penuel',
'perizzites',
'pi_hahiroth',
'pick',
'plague',
'present',
'prophecy',
'prophet',
'purify',
'reaiah',
'rechab',
'remaliah',
'remove',
'right',
'roll',
'run',
'save',
'senir',
'serve',
'seven',
'shem',
'shephatiah',
'shepherd',
'shiloh',
'shout',
'shunammite',
'solomon_s',
'strength',
'submit',
'tahpanhes',
'talmai',
'tekoa',
'tekoite',
'test',
'theophilus',
'thessalonica',
'throw',
'tiglath_pileser',
'titus',
'trust',
'truth',
'unni',
'uri',
'walk',
'western',
'witness',
'work',
'write',
'zabad',
'zedekiah_s',
'zemaraim',
'daniel',
'esther',
'baruch',
'lamb',
'mordecai',
'haman',
'job',
'eli',
'naomi',
'laban',
'festus',
'xerxes',
'achish',
'adonijah',
'darius',
'gedaliah',
'gehazi',
'goliath',
'neriah',
'rebekah',
'ruth',
'abednego',
'antioch',
'cain',
'kareah',
'mephibosheth',
'meshach',
'naaman',
'nicodemus',
'shadrach',
'silas',
'ahimaaz',
'ahithophel',
'ananias',
'artaxerxes',
'bless',
'deborah',
'glory',
'hallelujah',
'hamor',
'obed',
'roman',
'stephen',
'zimri',
'agrippa',
'amos',
'any',
'arphaxad',
'artemis',
'assyrians',
'basemath',
'bezalel',
'caesarea',
'cry',
'cut',
'delilah',
'ebiasaph',
'elkanah',
'enoch',
'ephron',
'gaal',
'hagrites',
'haman_s',
'hegai',
'helon',
'include',
'ish_bosheth',
'jediael',
'jerahmeel',
'jubilee',
'light',
'paul_s',
'pur',
'shobal',
'tirzah',
'troas',
'word',
'zebadiah',
'ziba',
'zichri',
'zohar',
'abdon',
'abidan',
'abinoam',
'abiud',
'abyss',
'achan',
'achshaph',
'acsah',
'adar',
'almon_diblathaim',
'ammon',
'amnon',
'ariel',
'arvad',
'assir',
'aware',
'baal_perazim',
'baanah',
'bakbukiah',
'balaam_s',
'beerothite',
'belonging',
'belshazzar',
'benjamin_s',
'beth_jeshimoth',
'binnui',
'blow',
'branch',
'buy',
'casiphia',
'cilicia',
'construct',
'corinth',
'corinthians',
'cornelius',
'crete',
'derbe',
'dimon',
'east',
'ebed',
'ebed_melech',
'ebenezer',
'eight',
'elasah',
'eliakim_s',
'elimelech',
'elizabeth',
'eloi',
'ephlal',
'esau_s',
'ethan',
'father_s',
'galal',
'galileans',
'gazez',
'gemariah',
'genubath',
'gershonite',
'gideoni',
'gileadites',
'god_fearing',
'gudgodah',
'hammedatha',
'hanamel',
'hannah',
'hathach',
'henadad',
'horesh',
'horonaim',
'hosah',
'hosea',
'hushai',
'husham',
'iconium',
'immer',
'ithamar',
'jabesh_gilead',
'jahath',
'japheth',
'japhia',
'jared',
'jeroham',
'joiarib',
'jokshan',
'jonadab',
'josiah_s',
'kadmiel',
'kue',
'laish',
'large',
'leshem',
'lystra',
'mahalalel',
'makkedah',
'manahathites',
'martha',
'meshelemiah',
'micah',
'micah_s',
'midianite',
'moabitess',
'moza',
'nazirite',
'nebuzaradan',
'nehemiah',
'netophathites',
'nicolaitans',
'observe',
'oholibamah',
'olives',
'overlay',
'peninnah',
'philippi',
'plunder',
'presence',
'purim',
'rabshakeh',
'rebekah_s',
'repay',
'rephaiah',
'restore',
'romans',
'samaritan',
'sanballat',
'seled',
'shebna',
'shemiramoth',
'sheshbazzar',
'shethar_bozenai',
'shilonite',
'shoot',
'sisera',
'sismai',
'six',
'stephanas',
'syria',
'tahpenes',
'tattenai',
'temanite',
'terror',
'tibni',
'tobijah',
'treason',
'tubal_cain',
'vashti',
'watchman',
'zalmunna',
'zebah',
'zerahiah',
'zilpah',
'zorathites',
'abanah',
'abandon',
'abba',
'abdi',
'abel_keramim',
'abi',
'abiathar_s',
'abimelech_s',
'abinadab_s',
'abishag',
'abishua',
'abram_s',
'abstain',
'abundant',
'acacias',
'accept',
'achaicus',
'act',
'acts',
'adah',
'add',
'addar',
'adiel',
'admatha',
'administer',
'adoni_zedek',
'adullamite',
'advocate',
'agag',
'agagite',
'agee',
'ahab_s',
'ahasbai',
'ahava',
'aher',
'ahiezer',
'ahimoth',
'ahinadab',
'ahiram',
'ahiramite',
'ahishahar',
'ahithophel_s',
'ahumai',
'aiath',
'aijalon',
'aim',
'ain',
'akan',
'alexander',
'allow',
'almodad',
'alphaeus',
'already',
'alush',
'amalekite',
'amana',
'amasai',
'ammihud',
'amnon_s',
'amphipolis',
'amramites',
'anab',
'anah',
'anaharath',
'anakites',
'anan',
'ananiah',
'ancient',
'anem',
'anguish'
);

commit;