-- Add 39 book-level and 11 episode-level Old Testament geography items.
-- Importance follows geographic centrality: essential book geography is
-- weighted above supporting context, which is weighted above episode detail.

begin;

do $$
begin
  if to_regclass('public.ot_generated_questions') is null
     or to_regclass('public.obs_biblical_books') is null
     or to_regclass('public.question_coverage_targets') is null
     or to_regclass('public.obs_schema_backups') is null
     or to_regclass('public.obs_admin_question_bank_audit') is null
     or to_regclass('public.obs_question_distractor_quality_audit') is null
     or to_regclass('public.obs_semantic_distractor_reviews') is null
  then
    raise exception using
      errcode = 'P0001',
      message = 'Old Testament geography batch prerequisites are missing.';
  end if;
end
$$;

insert into public.obs_schema_backups (
  backup_tag,
  object_schema,
  object_name,
  object_type,
  definition
)
select
  '20260729_ot_geography_centrality_question_batch',
  'public',
  'question_coverage_targets',
  'data',
  jsonb_agg(to_jsonb(target) order by target.book_code)::text
from public.question_coverage_targets target
where target.dimension_key = 'geography_nations'
  and target.book_code in (
    'LEV', 'DEU', 'JOB', 'PSA', 'PRO', 'ECC',
    'SNG', 'JOL', 'HAB', 'ZEP', 'MAL'
  )
having not exists (
  select 1
  from public.obs_schema_backups backup
  where backup.backup_tag = '20260729_ot_geography_centrality_question_batch'
    and backup.object_schema = 'public'
    and backup.object_name = 'question_coverage_targets'
    and backup.object_type = 'data'
);

do $$
declare
  backup_count integer;
  saved_row_count integer;
begin
  select count(*)
  into backup_count
  from public.obs_schema_backups
  where backup_tag = '20260729_ot_geography_centrality_question_batch'
    and object_schema = 'public'
    and object_name = 'question_coverage_targets'
    and object_type = 'data';

  select jsonb_array_length(definition::jsonb)
  into saved_row_count
  from public.obs_schema_backups
  where backup_tag = '20260729_ot_geography_centrality_question_batch'
    and object_schema = 'public'
    and object_name = 'question_coverage_targets'
    and object_type = 'data';

  if backup_count <> 1 or saved_row_count <> 11 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Geography target backup failed: backups=%s saved_rows=%s.',
        backup_count,
        coalesce(saved_row_count, 0)
      );
  end if;
end
$$;

update public.question_coverage_targets target
set
  minimum_active_questions = correction.minimum_active_questions,
  target_active_questions = correction.target_active_questions,
  priority = correction.priority,
  rationale = correction.rationale,
  updated_at = now()
from (
  values
    ('LEV', 'geography_nations', 1, 1, 'optional', 'Sinai and the tabernacle locate Leviticus within Israel''s journey.'),
    ('DEU', 'geography_nations', 1, 3, 'standard', 'The plains of Moab and the Jordan are essential to Deuteronomy''s covenant-renewal setting.'),
    ('JOB', 'geography_nations', 1, 1, 'optional', 'The land of Uz is useful setting context but not a primary route through Job.'),
    ('PSA', 'geography_nations', 1, 2, 'standard', 'Zion and Jerusalem are recurring geographic centers of worship and royal hope in Psalms.'),
    ('PRO', 'geography_nations', 1, 1, 'optional', 'Public settings such as the city gate support interpretation of Proverbs.'),
    ('ECC', 'geography_nations', 1, 1, 'optional', 'Jerusalem supplies the Teacher''s stated royal setting in Ecclesiastes.'),
    ('SNG', 'geography_nations', 1, 1, 'optional', 'Geographic imagery contributes to Song of Songs without governing its structure.'),
    ('JOL', 'geography_nations', 1, 2, 'standard', 'Zion, Jerusalem, and Judah are central to Joel''s judgment and restoration.'),
    ('HAB', 'geography_nations', 1, 2, 'standard', 'Judah and the rise of Babylon form the geopolitical crisis behind Habakkuk.'),
    ('ZEP', 'geography_nations', 1, 2, 'standard', 'Judah and Jerusalem anchor Zephaniah''s judgment among the surrounding nations.'),
    ('MAL', 'geography_nations', 1, 1, 'optional', 'Restored Judah and its functioning temple supply the setting for Malachi''s rebukes.')
) correction(
  book_code,
  dimension_key,
  minimum_active_questions,
  target_active_questions,
  priority,
  rationale
)
where target.book_code = correction.book_code
  and target.dimension_key = correction.dimension_key;

with seed(question_type, dedupe_key, payload) as (
  values
    ('geography_book_mcq_v1', 'geography_v1|GEN|patriarchal_route', '{"prompt":"Which geographic movement best describes the family story in Genesis after the call of Abram?","choices":[{"id":"A","text":"From Mesopotamia and Haran into Canaan, with the family eventually going down to Egypt"},{"id":"B","text":"From Egypt through Sinai and the wilderness toward the plains of Moab"},{"id":"C","text":"From Shiloh through the Philistine frontier and wilderness to Jerusalem"},{"id":"D","text":"From Babylon through the Persian provinces to rebuilt Jerusalem"}],"correct_choice_id":"A","correct_answer":"From Mesopotamia and Haran into Canaan, with the family eventually going down to Egypt","book_code":"GEN","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|GEN|patriarchal_route","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":400,"irt_a":1,"irt_b":-1,"importance_context":94,"importance_conceptual":94,"routing_score":94,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Gen 11:31-12:7; 46:1-7","explanation":"Genesis follows Abram from Mesopotamia and Haran into Canaan and ends with Jacob''s family living in Egypt.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|EXO|major_settings_exclusion', '{"prompt":"Which place is not a major setting in Exodus?","choices":[{"id":"A","text":"Egypt"},{"id":"B","text":"Babylon"},{"id":"C","text":"Midian"},{"id":"D","text":"Sinai"}],"correct_choice_id":"B","correct_answer":"Babylon","book_code":"EXO","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|EXO|major_settings_exclusion","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":395,"irt_a":1,"irt_b":-1.05,"importance_context":96,"importance_conceptual":93,"routing_score":94,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":true,"exact_chapter_recall_required":false,"source_ref":"Exod 1:1-14; 14:1-31; 19:1-2","explanation":"Exodus moves from Egypt through the sea and wilderness to Mount Sinai. Babylon is not a setting in the book.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|LEV|sinai_tabernacle_setting', '{"prompt":"Where are the instructions of Leviticus situated within Israel''s journey?","choices":[{"id":"A","text":"On the plains of Moab as Israel prepares to cross the Jordan"},{"id":"B","text":"At Shiloh after the land has been divided among the tribes"},{"id":"C","text":"At Israel''s camp at Sinai, centered on the tabernacle"},{"id":"D","text":"At the Jerusalem temple after Solomon becomes king"}],"correct_choice_id":"C","correct_answer":"At Israel''s camp at Sinai, centered on the tabernacle","book_code":"LEV","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|LEV|sinai_tabernacle_setting","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":420,"irt_a":1,"irt_b":-0.8,"importance_context":76,"importance_conceptual":70,"routing_score":72,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Lev 1:1; 25:1; 26:46; 27:34","explanation":"Leviticus presents the LORD''s instructions at Sinai, with worship centered on the tabernacle.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|NUM|wilderness_route', '{"prompt":"Which route best summarizes the movement of Israel in Numbers?","choices":[{"id":"A","text":"From Canaan back to Egypt by way of the Philistine coast"},{"id":"B","text":"From Babylon to Jerusalem under Persian protection"},{"id":"C","text":"From Shiloh to Gibeah and then to Jerusalem"},{"id":"D","text":"From Sinai through the wilderness toward the plains of Moab"}],"correct_choice_id":"D","correct_answer":"From Sinai through the wilderness toward the plains of Moab","book_code":"NUM","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|NUM|wilderness_route","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":405,"irt_a":1,"irt_b":-0.95,"importance_context":93,"importance_conceptual":90,"routing_score":91,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Num 1:1; 10:11-12; 22:1; 36:13","explanation":"Numbers begins at Sinai, follows Israel through the wilderness, and ends on the plains of Moab.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|DEU|geographic_standpoint', '{"prompt":"Which description best captures the geographic standpoint of Deuteronomy?","choices":[{"id":"A","text":"Israel is east of the Jordan on the plains of Moab, looking toward Canaan"},{"id":"B","text":"Israel is at Mount Sinai immediately after leaving Egypt"},{"id":"C","text":"Israel is gathered at Shiloh after Joshua divides the land"},{"id":"D","text":"Judah is in Babylon preparing to return to Jerusalem"}],"correct_choice_id":"A","correct_answer":"Israel is east of the Jordan on the plains of Moab, looking toward Canaan","book_code":"DEU","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|DEU|geographic_standpoint","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":405,"irt_a":1,"irt_b":-0.95,"importance_context":94,"importance_conceptual":91,"routing_score":92,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Deut 1:1-5; 34:1-8","explanation":"Moses addresses Israel on the plains of Moab before the people cross the Jordan into Canaan.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JOS|jordan_entry', '{"prompt":"Which geographic movement launches the main action of Joshua?","choices":[{"id":"A","text":"Israel crosses the Euphrates and enters Babylon"},{"id":"B","text":"Israel crosses the Jordan from the east and enters Canaan"},{"id":"C","text":"Israel leaves Jerusalem and settles in Egypt"},{"id":"D","text":"Israel sails from Joppa and arrives in Nineveh"}],"correct_choice_id":"B","correct_answer":"Israel crosses the Jordan from the east and enters Canaan","book_code":"JOS","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JOS|jordan_entry","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":400,"irt_a":1,"irt_b":-1,"importance_context":94,"importance_conceptual":92,"routing_score":93,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Josh 1:1-2; 3:14-17","explanation":"Joshua''s main narrative begins as Israel crosses the Jordan and enters the promised land.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JDG|tribal_borderlands', '{"prompt":"Which setting best describes most of the events in Judges?","choices":[{"id":"A","text":"The Judean exile communities living throughout Babylonia and Persia"},{"id":"B","text":"The Persian royal court at Susa and the provinces of the empire"},{"id":"C","text":"Israel''s tribal territories in Canaan and their surrounding borderlands"},{"id":"D","text":"Israel''s camp at Sinai and the wilderness route toward Moab"}],"correct_choice_id":"C","correct_answer":"Israel''s tribal territories in Canaan and their surrounding borderlands","book_code":"JDG","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JDG|tribal_borderlands","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":86,"importance_conceptual":82,"routing_score":83,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Judg 1:1-36; 2:6-23","explanation":"Judges moves among Israel''s tribal territories and neighboring peoples in and around Canaan.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|RUT|moab_bethlehem_route', '{"prompt":"Which movement provides the geographic frame for Ruth?","choices":[{"id":"A","text":"From Egypt to Mount Sinai"},{"id":"B","text":"From Susa to Jerusalem"},{"id":"C","text":"From Joppa to Nineveh"},{"id":"D","text":"From Moab to Bethlehem in Judah"}],"correct_choice_id":"D","correct_answer":"From Moab to Bethlehem in Judah","book_code":"RUT","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|RUT|moab_bethlehem_route","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":405,"irt_a":1,"irt_b":-0.95,"importance_context":86,"importance_conceptual":80,"routing_score":82,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Ruth 1:1-22","explanation":"Naomi returns from Moab to Bethlehem, and Ruth accompanies her into Judah.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|1SA|major_settings', '{"prompt":"Which group contains only important settings in 1 Samuel?","choices":[{"id":"A","text":"Shiloh, Gibeah, the Philistine frontier, and the wilderness of Judah"},{"id":"B","text":"Babylon, Susa, Nineveh, and the Kebar canal"},{"id":"C","text":"Mount Sinai, Kadesh-barnea, Moab, and Mount Nebo"},{"id":"D","text":"Samaria, Damascus, Babylon, and the Persian court"}],"correct_choice_id":"A","correct_answer":"Shiloh, Gibeah, the Philistine frontier, and the wilderness of Judah","book_code":"1SA","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|1SA|major_settings","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":425,"irt_a":1,"irt_b":-0.75,"importance_context":84,"importance_conceptual":80,"routing_score":81,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"1 Sam 1:3; 10:26; 17:1-3; 23:14","explanation":"First Samuel moves from Shiloh through Saul''s center at Gibeah, conflict with Philistia, and David''s wilderness flight.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|2SA|hebron_to_jerusalem', '{"prompt":"David''s rule in 2 Samuel shifts from which city to which city?","choices":[{"id":"A","text":"From Shiloh to Bethel"},{"id":"B","text":"From Hebron to Jerusalem"},{"id":"C","text":"From Samaria to Damascus"},{"id":"D","text":"From Bethlehem to Babylon"}],"correct_choice_id":"B","correct_answer":"From Hebron to Jerusalem","book_code":"2SA","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|2SA|hebron_to_jerusalem","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":405,"irt_a":1,"irt_b":-0.95,"importance_context":91,"importance_conceptual":88,"routing_score":89,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"2 Sam 2:1-4; 5:1-10","explanation":"David first reigns over Judah from Hebron and later establishes Jerusalem as the capital of all Israel.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|1KI|divided_kingdom_geography', '{"prompt":"Which geographic division becomes central after Solomon''s death in 1 Kings?","choices":[{"id":"A","text":"Edom divides into eastern and western kingdoms"},{"id":"B","text":"Babylon separates from Persia and occupies Egypt"},{"id":"C","text":"The northern kingdom of Israel separates from Judah in the south"},{"id":"D","text":"Philistia divides Jerusalem from the tribe of Benjamin"}],"correct_choice_id":"C","correct_answer":"The northern kingdom of Israel separates from Judah in the south","book_code":"1KI","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|1KI|divided_kingdom_geography","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":95,"importance_conceptual":94,"routing_score":94,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"1 Kgs 12:1-24; 16:23-24","explanation":"After Solomon, the kingdom divides into northern Israel and southern Judah; Samaria later becomes the northern capital.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|2KI|two_capitals_fall', '{"prompt":"Which two royal capitals fall to foreign empires in 2 Kings?","choices":[{"id":"A","text":"Damascus falls to Egypt, and Nineveh falls to Persia"},{"id":"B","text":"Hebron falls to Moab, and Bethel falls to Edom"},{"id":"C","text":"Susa falls to Greece, and Babylon falls to Rome"},{"id":"D","text":"Samaria falls to Assyria, and Jerusalem falls to Babylon"}],"correct_choice_id":"D","correct_answer":"Samaria falls to Assyria, and Jerusalem falls to Babylon","book_code":"2KI","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|2KI|two_capitals_fall","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":97,"importance_conceptual":96,"routing_score":96,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"2 Kgs 17:5-6; 25:1-11","explanation":"Second Kings narrates Assyria''s capture of Samaria and Babylon''s later destruction of Jerusalem.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|1CH|jerusalem_focus', '{"prompt":"Which city becomes the geographic focus of David''s reign in 1 Chronicles?","choices":[{"id":"A","text":"Jerusalem"},{"id":"B","text":"Samaria"},{"id":"C","text":"Susa"},{"id":"D","text":"Nineveh"}],"correct_choice_id":"A","correct_answer":"Jerusalem","book_code":"1CH","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|1CH|jerusalem_focus","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":84,"importance_conceptual":80,"routing_score":81,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"1 Chr 11:4-9; 15:1-3; 22:1-5","explanation":"First Chronicles centers David''s kingship, the ark, and temple preparation in Jerusalem.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|2CH|judah_temple_focus', '{"prompt":"Which geographic and political center receives the main attention in 2 Chronicles?","choices":[{"id":"A","text":"The northern kingdom and its capital at Samaria"},{"id":"B","text":"Judah and the temple in Jerusalem"},{"id":"C","text":"The Assyrian court and the city of Nineveh"},{"id":"D","text":"The Persian provinces surrounding Susa"}],"correct_choice_id":"B","correct_answer":"Judah and the temple in Jerusalem","book_code":"2CH","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|2CH|judah_temple_focus","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":420,"irt_a":1,"irt_b":-0.8,"importance_context":87,"importance_conceptual":84,"routing_score":85,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"2 Chr 1:1-6; 10:16-19; 36:15-23","explanation":"Second Chronicles concentrates on Judah''s kings and the temple in Jerusalem through exile and the decree to return.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|EZR|exile_to_jerusalem', '{"prompt":"Which movement provides the broad geographic frame for Ezra?","choices":[{"id":"A","text":"Israelite tribes travel from Egypt to Mount Sinai"},{"id":"B","text":"Judean soldiers travel from Jerusalem to conquer Samaria"},{"id":"C","text":"Jewish exiles travel from the Babylonian and Persian world to Jerusalem"},{"id":"D","text":"Assyrian officials travel from Nineveh to rebuild Babylon"}],"correct_choice_id":"C","correct_answer":"Jewish exiles travel from the Babylonian and Persian world to Jerusalem","book_code":"EZR","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|EZR|exile_to_jerusalem","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":91,"importance_conceptual":88,"routing_score":89,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Ezra 1:1-5; 7:6-9","explanation":"Ezra recounts returns from exile to Jerusalem for temple restoration and covenant reform.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|NEH|susa_to_jerusalem', '{"prompt":"Which journey begins Nehemiah''s work?","choices":[{"id":"A","text":"From Jerusalem to the Assyrian court at Nineveh"},{"id":"B","text":"From Egypt to the wilderness of Sinai"},{"id":"C","text":"From Bethlehem to the land of Moab"},{"id":"D","text":"From the Persian court at Susa to Jerusalem"}],"correct_choice_id":"D","correct_answer":"From the Persian court at Susa to Jerusalem","book_code":"NEH","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|NEH|susa_to_jerusalem","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":90,"importance_conceptual":86,"routing_score":87,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Neh 1:1-4; 2:1-11","explanation":"Nehemiah leaves his service in Susa and travels to Jerusalem to rebuild the city''s walls.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|EST|susa_persian_court', '{"prompt":"Where does most of the court action in Esther take place?","choices":[{"id":"A","text":"At Susa in the Persian Empire"},{"id":"B","text":"At Samaria in the northern kingdom"},{"id":"C","text":"At Nineveh in the Assyrian Empire"},{"id":"D","text":"At Hebron during David''s early reign"}],"correct_choice_id":"A","correct_answer":"At Susa in the Persian Empire","book_code":"EST","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|EST|susa_persian_court","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":88,"importance_conceptual":82,"routing_score":84,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Esth 1:2; 2:5-8","explanation":"Esther is set chiefly at the Persian royal citadel in Susa.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JOB|land_of_uz', '{"prompt":"In which land does the opening narrative place Job?","choices":[{"id":"A","text":"The land of Goshen"},{"id":"B","text":"The land of Uz"},{"id":"C","text":"The plain of Shinar"},{"id":"D","text":"The hill country of Ephraim"}],"correct_choice_id":"B","correct_answer":"The land of Uz","book_code":"JOB","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JOB|land_of_uz","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":485,"irt_a":1,"irt_b":-0.15,"importance_context":58,"importance_conceptual":48,"routing_score":51,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Job 1:1","explanation":"The book introduces Job as a man living in the land of Uz.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|PSA|zion_jerusalem_focus', '{"prompt":"Which location is repeatedly celebrated in Psalms as the city of God and a center of worship and royal hope?","choices":[{"id":"A","text":"Nineveh and Asshur"},{"id":"B","text":"Susa and Persepolis"},{"id":"C","text":"Zion and Jerusalem"},{"id":"D","text":"Babylon and Ur"}],"correct_choice_id":"C","correct_answer":"Zion and Jerusalem","book_code":"PSA","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|PSA|zion_jerusalem_focus","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":420,"irt_a":1,"irt_b":-0.8,"importance_context":86,"importance_conceptual":85,"routing_score":85,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Ps 2:6; 48:1-3; 87:1-3; 122:1-5","explanation":"Many psalms present Zion or Jerusalem as the place of God''s rule, worship, and royal hope.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|PRO|city_gates', '{"prompt":"Which public setting appears repeatedly in Proverbs as a place of instruction, commerce, and judgment?","choices":[{"id":"A","text":"The wilderness camp"},{"id":"B","text":"The royal tombs"},{"id":"C","text":"The battlefield watchtowers"},{"id":"D","text":"The city gates"}],"correct_choice_id":"D","correct_answer":"The city gates","book_code":"PRO","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|PRO|city_gates","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":490,"irt_a":1,"irt_b":-0.1,"importance_context":55,"importance_conceptual":46,"routing_score":49,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Prov 1:20-21; 8:1-3; 22:22; 31:23","explanation":"Proverbs repeatedly uses the city gates as a public setting for wisdom, legal decisions, and community life.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|ECC|jerusalem_royal_context', '{"prompt":"Which city supplies the Teacher''s stated royal setting in Ecclesiastes?","choices":[{"id":"A","text":"Jerusalem"},{"id":"B","text":"Samaria"},{"id":"C","text":"Nineveh"},{"id":"D","text":"Susa"}],"correct_choice_id":"A","correct_answer":"Jerusalem","book_code":"ECC","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|ECC|jerusalem_royal_context","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":495,"irt_a":1,"irt_b":-0.05,"importance_context":53,"importance_conceptual":44,"routing_score":47,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Eccl 1:1, 12","explanation":"The Teacher identifies himself with royal rule over Israel in Jerusalem.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|SNG|poetic_places_exclusion', '{"prompt":"Which place is not part of the geographic imagery in Song of Songs?","choices":[{"id":"A","text":"Jerusalem"},{"id":"B","text":"Babylon"},{"id":"C","text":"Lebanon"},{"id":"D","text":"En Gedi"}],"correct_choice_id":"B","correct_answer":"Babylon","book_code":"SNG","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|SNG|poetic_places_exclusion","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":505,"irt_a":1,"irt_b":0.05,"importance_context":48,"importance_conceptual":38,"routing_score":41,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":true,"exact_chapter_recall_required":false,"source_ref":"Song 1:5, 14; 4:8","explanation":"Song of Songs names Jerusalem, Lebanon, and En Gedi in its poetry, but not Babylon.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|ISA|zion_assyrian_crisis', '{"prompt":"Which city and region form the central earthly setting of Isaiah''s warnings and hopes?","choices":[{"id":"A","text":"Nineveh and the heartland of Assyria"},{"id":"B","text":"Susa and the provinces of Persia"},{"id":"C","text":"Jerusalem or Zion and the kingdom of Judah"},{"id":"D","text":"Samaria alone, with no attention to Judah"}],"correct_choice_id":"C","correct_answer":"Jerusalem or Zion and the kingdom of Judah","book_code":"ISA","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|ISA|zion_assyrian_crisis","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":94,"importance_conceptual":93,"routing_score":93,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Isa 1:1, 8-9; 2:1-4; 36:1-2","explanation":"Isaiah addresses Judah and Jerusalem, especially Zion, amid Assyrian pressure and promises of restoration.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JER|judah_fall_and_dispersion', '{"prompt":"Which geographic movement best fits the closing crisis of Jeremiah?","choices":[{"id":"A","text":"Samaria conquers Judah and moves its people to Nineveh"},{"id":"B","text":"Persia destroys Babylon and forces Judah into Edom"},{"id":"C","text":"Egypt captures Assyria and settles its people in Jerusalem"},{"id":"D","text":"Jerusalem falls, people are exiled to Babylon, and a remnant flees to Egypt"}],"correct_choice_id":"D","correct_answer":"Jerusalem falls, people are exiled to Babylon, and a remnant flees to Egypt","book_code":"JER","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JER|judah_fall_and_dispersion","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":425,"irt_a":1,"irt_b":-0.75,"importance_context":95,"importance_conceptual":92,"routing_score":93,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Jer 39:1-10; 43:1-7; 52:27-30","explanation":"Jeremiah''s closing crisis includes Jerusalem''s fall, Babylonian exile, and the flight of a remnant to Egypt.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|LAM|jerusalem_ruins', '{"prompt":"Which city''s destruction provides the setting and subject of Lamentations?","choices":[{"id":"A","text":"Jerusalem"},{"id":"B","text":"Nineveh"},{"id":"C","text":"Samaria"},{"id":"D","text":"Susa"}],"correct_choice_id":"A","correct_answer":"Jerusalem","book_code":"LAM","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|LAM|jerusalem_ruins","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":400,"irt_a":1,"irt_b":-1,"importance_context":94,"importance_conceptual":91,"routing_score":92,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Lam 1:1-4; 2:1-10","explanation":"Lamentations grieves over devastated Jerusalem and the suffering that followed its fall.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|EZE|babylon_and_jerusalem', '{"prompt":"Which two locations frame much of Ezekiel''s prophetic perspective?","choices":[{"id":"A","text":"The royal court in Susa and the city of Nineveh"},{"id":"B","text":"The exiles in Babylonia by the Kebar canal and the city of Jerusalem"},{"id":"C","text":"The wilderness of Sinai and the plains of Moab"},{"id":"D","text":"The city of Samaria and the island of Cyprus"}],"correct_choice_id":"B","correct_answer":"The exiles in Babylonia by the Kebar canal and the city of Jerusalem","book_code":"EZE","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|EZE|babylon_and_jerusalem","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":94,"importance_conceptual":92,"routing_score":93,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Ezek 1:1-3; 8:1-4; 40:1-2","explanation":"Ezekiel prophesies among exiles in Babylonia while many visions and messages concern Jerusalem.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|DAN|imperial_court_setting', '{"prompt":"Which setting best describes the court narratives in Daniel?","choices":[{"id":"A","text":"Israelite judges defending tribal Canaan"},{"id":"B","text":"Priests serving at the tabernacle on Mount Sinai"},{"id":"C","text":"Jewish exiles serving under Babylonian and Persian rule"},{"id":"D","text":"Judean farmers rebuilding walls under Roman rule"}],"correct_choice_id":"C","correct_answer":"Jewish exiles serving under Babylonian and Persian rule","book_code":"DAN","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|DAN|imperial_court_setting","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":92,"importance_conceptual":89,"routing_score":90,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Dan 1:1-7; 5:30-6:3","explanation":"Daniel''s court narratives follow Jewish exiles under Babylonian and then Persian imperial rule.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|HOS|northern_kingdom_audience', '{"prompt":"Which kingdom, often called Ephraim, is the main geographic and political focus of Hosea?","choices":[{"id":"A","text":"The southern kingdom of Judah alone"},{"id":"B","text":"The kingdom of Edom"},{"id":"C","text":"The Persian Empire"},{"id":"D","text":"The northern kingdom of Israel"}],"correct_choice_id":"D","correct_answer":"The northern kingdom of Israel","book_code":"HOS","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|HOS|northern_kingdom_audience","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":88,"importance_conceptual":84,"routing_score":85,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Hos 1:1; 4:1; 5:3","explanation":"Hosea chiefly addresses northern Israel, frequently referring to it as Ephraim.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JOL|zion_jerusalem_judah', '{"prompt":"Which place is central to Joel''s calls to repentance and promises of deliverance?","choices":[{"id":"A","text":"Zion or Jerusalem in Judah"},{"id":"B","text":"Nineveh in Assyria"},{"id":"C","text":"Susa in Persia"},{"id":"D","text":"Samaria in northern Israel"}],"correct_choice_id":"A","correct_answer":"Zion or Jerusalem in Judah","book_code":"JOL","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JOL|zion_jerusalem_judah","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":425,"irt_a":1,"irt_b":-0.75,"importance_context":82,"importance_conceptual":78,"routing_score":79,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Joel 1:14; 2:1, 15, 32; 3:1, 16-17","explanation":"Joel repeatedly addresses Zion, Jerusalem, and Judah in its warnings and promises.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|AMO|tekoa_to_bethel', '{"prompt":"Which geographic contrast helps locate Amos''s ministry?","choices":[{"id":"A","text":"He comes from Nineveh but prophesies chiefly in Babylon"},{"id":"B","text":"He comes from Tekoa in Judah but prophesies chiefly to northern Israel, including Bethel"},{"id":"C","text":"He comes from Susa but prophesies chiefly in Egypt"},{"id":"D","text":"He comes from Moab but prophesies chiefly in Edom"}],"correct_choice_id":"B","correct_answer":"He comes from Tekoa in Judah but prophesies chiefly to northern Israel, including Bethel","book_code":"AMO","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|AMO|tekoa_to_bethel","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":420,"irt_a":1,"irt_b":-0.8,"importance_context":86,"importance_conceptual":81,"routing_score":83,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Amos 1:1; 7:10-15","explanation":"Amos is from Tekoa in Judah, yet his central ministry is directed toward northern Israel.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|OBA|edom_and_jerusalem', '{"prompt":"Which two lands stand in sharp opposition in Obadiah?","choices":[{"id":"A","text":"Assyria and Babylon, especially Nineveh"},{"id":"B","text":"Egypt and Cush, especially Memphis"},{"id":"C","text":"Edom and Judah, especially Jerusalem"},{"id":"D","text":"Persia and Media, especially Susa"}],"correct_choice_id":"C","correct_answer":"Edom and Judah, especially Jerusalem","book_code":"OBA","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|OBA|edom_and_jerusalem","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":425,"irt_a":1,"irt_b":-0.75,"importance_context":89,"importance_conceptual":84,"routing_score":86,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Obad 1-4, 10-14, 17-21","explanation":"Obadiah condemns Edom for violence against Judah and Jerusalem and promises restoration for Zion.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|JON|joppa_sea_nineveh', '{"prompt":"Which route best summarizes Jonah''s geographic movement?","choices":[{"id":"A","text":"From Babylon to Susa and eventually to Jerusalem"},{"id":"B","text":"From Moab to Bethlehem and eventually to Hebron"},{"id":"C","text":"From Egypt to Sinai and eventually to the plains of Moab"},{"id":"D","text":"From Israel to Joppa and the sea, and eventually to Nineveh"}],"correct_choice_id":"D","correct_answer":"From Israel to Joppa and the sea, and eventually to Nineveh","book_code":"JON","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|JON|joppa_sea_nineveh","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":410,"irt_a":1,"irt_b":-0.9,"importance_context":91,"importance_conceptual":87,"routing_score":88,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Jonah 1:1-3, 15-17; 3:1-3","explanation":"Jonah travels to Joppa to flee by sea but is eventually sent to Nineveh.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|MIC|two_capitals', '{"prompt":"Which two capitals frame Micah''s indictments of Israel and Judah?","choices":[{"id":"A","text":"Samaria and Jerusalem"},{"id":"B","text":"Nineveh and Babylon"},{"id":"C","text":"Susa and Persepolis"},{"id":"D","text":"Damascus and Tyre"}],"correct_choice_id":"A","correct_answer":"Samaria and Jerusalem","book_code":"MIC","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|MIC|two_capitals","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":86,"importance_conceptual":82,"routing_score":83,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Mic 1:1, 5-9","explanation":"Micah announces judgment concerning Samaria in northern Israel and Jerusalem in Judah.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|NAM|nineveh_target', '{"prompt":"Which city''s fall is the geographic focus of Nahum?","choices":[{"id":"A","text":"Jerusalem"},{"id":"B","text":"Nineveh"},{"id":"C","text":"Samaria"},{"id":"D","text":"Susa"}],"correct_choice_id":"B","correct_answer":"Nineveh","book_code":"NAM","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|NAM|nineveh_target","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":405,"irt_a":1,"irt_b":-0.95,"importance_context":90,"importance_conceptual":85,"routing_score":87,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Nah 1:1; 2:8; 3:7","explanation":"Nahum announces and vividly portrays the fall of Nineveh, the Assyrian capital.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|HAB|judah_and_chaldeans', '{"prompt":"Which geopolitical setting drives Habakkuk''s complaints and the LORD''s answer?","choices":[{"id":"A","text":"A Persian invasion of Egypt and the fall of Susa"},{"id":"B","text":"A Philistine conquest of Babylon and the fall of Nineveh"},{"id":"C","text":"Violence in Judah and the rise of the Babylonian or Chaldean power"},{"id":"D","text":"A Moabite invasion of Assyria and the fall of Damascus"}],"correct_choice_id":"C","correct_answer":"Violence in Judah and the rise of the Babylonian or Chaldean power","book_code":"HAB","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|HAB|judah_and_chaldeans","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":435,"irt_a":1,"irt_b":-0.65,"importance_context":86,"importance_conceptual":83,"routing_score":84,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Hab 1:2-11","explanation":"Habakkuk laments violence and hears that the Chaldeans are being raised up as an instrument of judgment.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|ZEP|judah_jerusalem_and_nations', '{"prompt":"Which place stands at the center of Zephaniah''s judgment before the book turns to surrounding nations?","choices":[{"id":"A","text":"Persia and Susa"},{"id":"B","text":"Assyria and Babylon alone"},{"id":"C","text":"Egypt and Memphis"},{"id":"D","text":"Judah and Jerusalem"}],"correct_choice_id":"D","correct_answer":"Judah and Jerusalem","book_code":"ZEP","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|ZEP|judah_jerusalem_and_nations","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":430,"irt_a":1,"irt_b":-0.7,"importance_context":82,"importance_conceptual":78,"routing_score":79,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Zeph 1:4-13; 2:4-15; 3:1-8","explanation":"Zephaniah begins with judgment on Judah and Jerusalem and then addresses neighboring nations.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|HAG|restored_jerusalem_temple', '{"prompt":"Which city and building project provide the setting for Haggai?","choices":[{"id":"A","text":"Jerusalem and the rebuilding of the temple"},{"id":"B","text":"Samaria and the rebuilding of its royal palace"},{"id":"C","text":"Nineveh and the rebuilding of its walls"},{"id":"D","text":"Hebron and the rebuilding of David''s tomb"}],"correct_choice_id":"A","correct_answer":"Jerusalem and the rebuilding of the temple","book_code":"HAG","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|HAG|restored_jerusalem_temple","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":88,"importance_conceptual":84,"routing_score":85,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Hag 1:2-8, 14; 2:3-9","explanation":"Haggai addresses the returned community in Jerusalem and urges completion of the temple.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|ZEC|jerusalem_restoration', '{"prompt":"Which city is the central location of Zechariah''s restoration visions and temple encouragement?","choices":[{"id":"A","text":"Samaria"},{"id":"B","text":"Jerusalem"},{"id":"C","text":"Nineveh"},{"id":"D","text":"Susa"}],"correct_choice_id":"B","correct_answer":"Jerusalem","book_code":"ZEC","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|ZEC|jerusalem_restoration","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":415,"irt_a":1,"irt_b":-0.85,"importance_context":90,"importance_conceptual":87,"routing_score":88,"geography_centrality":"essential","importance_rationale":"Book-level geography needed to follow the main plot, political setting, or prophetic audience.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Zech 1:12-17; 2:1-5; 8:1-8","explanation":"Zechariah''s visions repeatedly concern Jerusalem, its temple, and its future restoration.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_book_mcq_v1', 'geography_v1|MAL|restored_temple_context', '{"prompt":"Which setting best fits Malachi''s rebukes of priests, offerings, and covenant unfaithfulness?","choices":[{"id":"A","text":"Israel at Sinai before the tabernacle is built"},{"id":"B","text":"Northern Israel before the kingdom divides"},{"id":"C","text":"Restored Judah with functioning temple and altar worship"},{"id":"D","text":"Jewish exiles serving in the court at Babylon"}],"correct_choice_id":"C","correct_answer":"Restored Judah with functioning temple and altar worship","book_code":"MAL","dimension_key":"geography_nations","question_family":"book_geography_overview","stem_family":"geography_v1|MAL|restored_temple_context","assessment_role":"baseline","baseline_eligible":true,"retest_stage":"foundation","difficulty_estimate":435,"irt_a":1,"irt_b":-0.65,"importance_context":76,"importance_conceptual":70,"routing_score":72,"geography_centrality":"supporting","importance_rationale":"Geography supports interpretation of the book but is not its main narrative framework.","knowledge_granularity":"book_geography_overview","retrieval_target":"book_setting","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Mal 1:6-14; 2:11; 3:1, 10","explanation":"Malachi addresses a restored community in Judah whose temple worship and covenant life have become corrupt.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|EXO|moses_flees_midian', '{"prompt":"To what land does Moses flee after killing the Egyptian?","choices":[{"id":"A","text":"Moab"},{"id":"B","text":"Edom"},{"id":"C","text":"Philistia"},{"id":"D","text":"Midian"}],"correct_choice_id":"D","correct_answer":"Midian","book_code":"EXO","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|EXO|moses_flees_midian","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":495,"irt_a":1,"irt_b":-0.05,"importance_context":58,"importance_conceptual":45,"routing_score":49,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Exod 2:11-22","explanation":"Moses flees from Pharaoh to Midian, where he lives before returning to Egypt.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|NUM|spies_from_paran', '{"prompt":"From which wilderness does Moses send the spies to explore Canaan?","choices":[{"id":"A","text":"The wilderness of Paran"},{"id":"B","text":"The wilderness of Zin"},{"id":"C","text":"The wilderness of Shur"},{"id":"D","text":"The wilderness of Tekoa"}],"correct_choice_id":"A","correct_answer":"The wilderness of Paran","book_code":"NUM","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|NUM|spies_from_paran","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":505,"irt_a":1,"irt_b":0.05,"importance_context":56,"importance_conceptual":42,"routing_score":46,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Num 12:16-13:3","explanation":"Israel camps in the wilderness of Paran when Moses sends the spies into Canaan.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|DEU|moses_views_from_nebo', '{"prompt":"From which mountain does Moses view the promised land near the end of Deuteronomy?","choices":[{"id":"A","text":"Mount Carmel"},{"id":"B","text":"Mount Nebo"},{"id":"C","text":"Mount Tabor"},{"id":"D","text":"Mount Gerizim"}],"correct_choice_id":"B","correct_answer":"Mount Nebo","book_code":"DEU","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|DEU|moses_views_from_nebo","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":500,"irt_a":1,"irt_b":0,"importance_context":58,"importance_conceptual":46,"routing_score":50,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Deut 34:1-4","explanation":"Moses ascends Mount Nebo and views the land before his death.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|JOS|covenant_renewal_shechem', '{"prompt":"At which city does Joshua gather Israel for the covenant-renewal assembly near the end of the book?","choices":[{"id":"A","text":"Jericho"},{"id":"B","text":"Gibeon"},{"id":"C","text":"Shechem"},{"id":"D","text":"Hebron"}],"correct_choice_id":"C","correct_answer":"Shechem","book_code":"JOS","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|JOS|covenant_renewal_shechem","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":500,"irt_a":1,"irt_b":0,"importance_context":62,"importance_conceptual":54,"routing_score":56,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Josh 24:1, 25","explanation":"Joshua gathers the tribes at Shechem and renews the covenant there.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|JDG|sisera_kishon', '{"prompt":"Near which river is Sisera''s army swept into defeat in the account of Deborah and Barak?","choices":[{"id":"A","text":"The Jordan River"},{"id":"B","text":"The Arnon River"},{"id":"C","text":"The Euphrates River"},{"id":"D","text":"The Kishon River"}],"correct_choice_id":"D","correct_answer":"The Kishon River","book_code":"JDG","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|JDG|sisera_kishon","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":515,"irt_a":1,"irt_b":0.15,"importance_context":52,"importance_conceptual":38,"routing_score":42,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Judg 4:7, 13; 5:21","explanation":"The battle is fought near the Kishon, which Deborah''s song describes as sweeping the enemy away.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|1SA|robe_cave_en_gedi', '{"prompt":"In what area does David cut off the corner of Saul''s robe while hiding in a cave?","choices":[{"id":"A","text":"The wilderness of En Gedi"},{"id":"B","text":"The wilderness of Paran"},{"id":"C","text":"The hill country of Bethel"},{"id":"D","text":"The plain of Jezreel"}],"correct_choice_id":"A","correct_answer":"The wilderness of En Gedi","book_code":"1SA","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|1SA|robe_cave_en_gedi","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":510,"irt_a":1,"irt_b":0.1,"importance_context":50,"importance_conceptual":34,"routing_score":39,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"1 Sam 24:1-4","explanation":"David and his men are hiding in a cave in the wilderness of En Gedi when Saul enters.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|2SA|first_capital_hebron', '{"prompt":"From which city does David first rule Judah before becoming king over all Israel?","choices":[{"id":"A","text":"Gibeah"},{"id":"B","text":"Hebron"},{"id":"C","text":"Bethlehem"},{"id":"D","text":"Jericho"}],"correct_choice_id":"B","correct_answer":"Hebron","book_code":"2SA","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|2SA|first_capital_hebron","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":490,"irt_a":1,"irt_b":-0.1,"importance_context":66,"importance_conceptual":57,"routing_score":60,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"2 Sam 2:1-4; 5:1-5","explanation":"David reigns over Judah from Hebron before moving his capital to Jerusalem.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|1KI|elijah_mount_carmel', '{"prompt":"On which mountain does Elijah confront the prophets of Baal?","choices":[{"id":"A","text":"Mount Tabor"},{"id":"B","text":"Mount Nebo"},{"id":"C","text":"Mount Carmel"},{"id":"D","text":"Mount Gerizim"}],"correct_choice_id":"C","correct_answer":"Mount Carmel","book_code":"1KI","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|1KI|elijah_mount_carmel","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":495,"irt_a":1,"irt_b":-0.05,"importance_context":68,"importance_conceptual":58,"routing_score":61,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"1 Kgs 18:19-40","explanation":"Elijah summons Israel and the prophets of Baal to Mount Carmel for the contest.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|2KI|naaman_jordan', '{"prompt":"In which river does Naaman wash after following Elisha''s instruction?","choices":[{"id":"A","text":"The Kishon River"},{"id":"B","text":"The Euphrates River"},{"id":"C","text":"The Nile River"},{"id":"D","text":"The Jordan River"}],"correct_choice_id":"D","correct_answer":"The Jordan River","book_code":"2KI","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|2KI|naaman_jordan","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":500,"irt_a":1,"irt_b":0,"importance_context":56,"importance_conceptual":42,"routing_score":46,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"2 Kgs 5:9-14","explanation":"Naaman washes seven times in the Jordan and is healed.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|EZR|gathering_at_ahava', '{"prompt":"At what river or canal does Ezra gather the returning group before the journey to Jerusalem?","choices":[{"id":"A","text":"The river or canal of Ahava"},{"id":"B","text":"The river of Kebar"},{"id":"C","text":"The brook Kidron"},{"id":"D","text":"The river Kishon"}],"correct_choice_id":"A","correct_answer":"The river or canal of Ahava","book_code":"EZR","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|EZR|gathering_at_ahava","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":520,"irt_a":1,"irt_b":0.2,"importance_context":46,"importance_conceptual":32,"routing_score":36,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Ezra 8:15, 21, 31","explanation":"Ezra gathers the travelers at Ahava, proclaims a fast, and begins the journey from there.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb),
    ('geography_episode_mcq_v1', 'geography_v1|JER|field_at_anathoth', '{"prompt":"Where is the field Jeremiah buys as a sign that property will again be possessed in the land?","choices":[{"id":"A","text":"Lachish"},{"id":"B","text":"Anathoth"},{"id":"C","text":"Tekoa"},{"id":"D","text":"Mizpah"}],"correct_choice_id":"B","correct_answer":"Anathoth","book_code":"JER","dimension_key":"geography_nations","question_family":"episode_geography","stem_family":"geography_v1|JER|field_at_anathoth","assessment_role":"adaptive","baseline_eligible":false,"retest_stage":"core","difficulty_estimate":515,"irt_a":1,"irt_b":0.15,"importance_context":55,"importance_conceptual":46,"routing_score":49,"geography_centrality":"episode","importance_rationale":"Episode-level location that clarifies a specific passage rather than the whole book.","knowledge_granularity":"episode_detail","retrieval_target":"episode_location","negative_stem":false,"exact_chapter_recall_required":false,"source_ref":"Jer 32:6-15","explanation":"Jeremiah buys a field at Anathoth as a sign of future restoration.","distractor_review":"same_category_manual","source_batch":"20260729_ot_geography_centrality_v1","content_version":"20260729_ot_geography_centrality_v1"}'::jsonb)
)
insert into public.ot_generated_questions (
  event_id,
  question_type,
  payload,
  dedupe_key
)
select
  null,
  seed.question_type,
  seed.payload,
  seed.dedupe_key
from seed
on conflict (question_type, dedupe_key) do nothing;

insert into public.obs_semantic_distractor_reviews (
  generated_question_id,
  review_status,
  same_semantic_category,
  obvious_elimination_present,
  expected_category,
  review_notes,
  reviewed_by,
  reviewed_at,
  updated_at
)
select
  question.id,
  'pass',
  true,
  false,
  'places, regions, nations, routes, or geopolitical units',
  'Manually authored geography set with same-category distractors.',
  '20260729_ot_geography_centrality_v1',
  now(),
  now()
from public.ot_generated_questions question
where question.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
on conflict (generated_question_id) do update
set
  review_status = excluded.review_status,
  same_semantic_category = excluded.same_semantic_category,
  obvious_elimination_present = excluded.obvious_elimination_present,
  expected_category = excluded.expected_category,
  review_notes = excluded.review_notes,
  reviewed_by = excluded.reviewed_by,
  reviewed_at = excluded.reviewed_at,
  updated_at = excluded.updated_at;

do $$
declare
  batch_count integer;
  book_count integer;
  covered_book_count integer;
  essential_count integer;
  supporting_count integer;
  episode_count integer;
  foundation_count integer;
  core_count integer;
  malformed_count integer;
  blocked_count integer;
  structurally_flagged integer;
  semantic_pass_count integer;
  correct_position_min integer;
  correct_position_max integer;
  essential_mean numeric;
  supporting_mean numeric;
  episode_mean numeric;
begin

  select
    count(*),
    count(*) filter (where payload->>'knowledge_granularity' = 'book_geography_overview'),
    count(distinct payload->>'book_code') filter (
      where payload->>'knowledge_granularity' = 'book_geography_overview'
    ),
    count(*) filter (where payload->>'geography_centrality' = 'essential'),
    count(*) filter (where payload->>'geography_centrality' = 'supporting'),
    count(*) filter (where payload->>'geography_centrality' = 'episode'),
    count(*) filter (where payload->>'retest_stage' = 'foundation'),
    count(*) filter (where payload->>'retest_stage' = 'core')
  into
    batch_count,
    book_count,
    covered_book_count,
    essential_count,
    supporting_count,
    episode_count,
    foundation_count,
    core_count
  from public.ot_generated_questions
  where payload->>'source_batch' = '20260729_ot_geography_centrality_v1';

  select count(*)
  into malformed_count
  from public.ot_generated_questions question
  where question.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
    and (
      question.payload->>'dimension_key' <> 'geography_nations'
      or jsonb_array_length(question.payload->'choices') <> 4
      or (
        select count(*)
        from jsonb_array_elements(question.payload->'choices') choice
        where choice->>'id' = question.payload->>'correct_choice_id'
      ) <> 1
      or (
        select count(distinct lower(btrim(choice->>'text')))
        from jsonb_array_elements(question.payload->'choices') choice
      ) <> 4
    );

  select count(*)
  into blocked_count
  from public.obs_admin_question_bank_audit audit
  where audit.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
    and (
      cardinality(audit.blocker_reasons) > 0
      or not audit.router_eligible
    );

  select count(*)
  into structurally_flagged
  from public.obs_question_distractor_quality_audit audit
  join public.ot_generated_questions question
    on question.id = audit.generated_question_id
  where question.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
    and audit.requires_review;

  select count(*)
  into semantic_pass_count
  from public.obs_semantic_distractor_reviews review
  join public.ot_generated_questions question
    on question.id = review.generated_question_id
  where question.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
    and review.review_status = 'pass'
    and review.same_semantic_category
    and not review.obvious_elimination_present;

  select min(position_count), max(position_count)
  into correct_position_min, correct_position_max
  from (
    select
      question.payload->>'correct_choice_id' as choice_id,
      count(*)::integer as position_count
    from public.ot_generated_questions question
    where question.payload->>'source_batch' = '20260729_ot_geography_centrality_v1'
    group by question.payload->>'correct_choice_id'
  ) positions;

  select
    avg(
      (
        (payload->>'importance_context')::numeric
        + (payload->>'importance_conceptual')::numeric
      ) / 2.0
    ) filter (where payload->>'geography_centrality' = 'essential'),
    avg(
      (
        (payload->>'importance_context')::numeric
        + (payload->>'importance_conceptual')::numeric
      ) / 2.0
    ) filter (where payload->>'geography_centrality' = 'supporting'),
    avg(
      (
        (payload->>'importance_context')::numeric
        + (payload->>'importance_conceptual')::numeric
      ) / 2.0
    ) filter (where payload->>'geography_centrality' = 'episode')
  into essential_mean, supporting_mean, episode_mean
  from public.ot_generated_questions
  where payload->>'source_batch' = '20260729_ot_geography_centrality_v1';

  if batch_count <> 50
     or book_count <> 39
     or covered_book_count <> 39
     or essential_count <> 33
     or supporting_count <> 6
     or episode_count <> 11
     or foundation_count <> 35
     or core_count <> 15
     or malformed_count <> 0
     or blocked_count <> 0
     or structurally_flagged <> 0
     or semantic_pass_count <> 50
     or correct_position_max - correct_position_min > 1
     or not (
       essential_mean > supporting_mean
       and supporting_mean > episode_mean
     )
  then
    raise exception using
      errcode = 'P0001',
      message = format(
        'Geography batch failed: total=%s book=%s books=%s centrality=%s/%s/%s stage=%s/%s malformed=%s blocked=%s structural=%s semantic=%s positions=%s-%s means=%s/%s/%s.',
        batch_count,
        book_count,
        covered_book_count,
        essential_count,
        supporting_count,
        episode_count,
        foundation_count,
        core_count,
        malformed_count,
        blocked_count,
        structurally_flagged,
        semantic_pass_count,
        correct_position_min,
        correct_position_max,
        round(essential_mean, 2),
        round(supporting_mean, 2),
        round(episode_mean, 2)
      );
  end if;
end
$$;

notify pgrst, 'reload schema';

commit;
